In [1]:
import os
from cuml.cluster import KMeans
import numpy as np
import torch
import pandas as pd
from utils import utils
from utils.utils import load_tensor

In [2]:
N_CLUSTERS = 42

METADATA_JSON_FILE = "embeddings/id_metadata.json"
TENSOR_DIRECTORY = "embeddings/uuid_embeddings/embeddings/"

In [ ]:

# loads uuid -> tensor (non-pooled, [N, D])
tensors = load_tensor(TENSOR_DIRECTORY, num_workers=16)

Loading cache from embeddings/cache

In [ ]:
import json
# AlbumID, AlbumName, TrackID, Artists (Json [{"id": "artist_id", "name": "artist_name"}])
with open(METADATA_JSON_FILE, "r", encoding="utf-8") as f:
  metadata_dict = json.load(f)

metadata_df = pd.DataFrame(metadata_dict)

metadata_df.head()

,AlbumID,AlbumName,TrackID,Artists
0,00016005-985e-4f11-b06d-e2f37fd65608,Taste me up!,1c2377e8-d3f1-4a8f-82c9-1fbede9de0d0,[{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae'...
1,00016005-985e-4f11-b06d-e2f37fd65608,Taste me up!,5c27d4ff-cf85-42fc-aa51-c9856be198b3,[{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae'...
2,00016005-985e-4f11-b06d-e2f37fd65608,Taste me up!,7ecfe8f0-9737-4fd5-9eaf-96770bd4226f,[{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae'...
3,00016005-985e-4f11-b06d-e2f37fd65608,Taste me up!,bd12b3ff-0b53-44da-b615-118ce11b6c22,[{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae'...
4,00016005-985e-4f11-b06d-e2f37fd65608,Taste me up!,c54e88c1-076e-4cc7-bce9-d861ada89ed2,[{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae'...

In [5]:
# metadata_df
# turn df into dict index with TrackID
metadata_dict = metadata_df.set_index("TrackID").to_dict(orient="index")

In [6]:
metadata_dict

{'1c2377e8-d3f1-4a8f-82c9-1fbede9de0d0': {'AlbumID': '00016005-985e-4f11-b06d-e2f37fd65608',
  'AlbumName': 'Taste me up!',
  'Artists': [{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae',
    'name': 'DiGiTAL WiNG'}]},
 '5c27d4ff-cf85-42fc-aa51-c9856be198b3': {'AlbumID': '00016005-985e-4f11-b06d-e2f37fd65608',
  'AlbumName': 'Taste me up!',
  'Artists': [{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae',
    'name': 'DiGiTAL WiNG'}]},
 '7ecfe8f0-9737-4fd5-9eaf-96770bd4226f': {'AlbumID': '00016005-985e-4f11-b06d-e2f37fd65608',
  'AlbumName': 'Taste me up!',
  'Artists': [{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae',
    'name': 'DiGiTAL WiNG'}]},
 'bd12b3ff-0b53-44da-b615-118ce11b6c22': {'AlbumID': '00016005-985e-4f11-b06d-e2f37fd65608',
  'AlbumName': 'Taste me up!',
  'Artists': [{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae',
    'name': 'DiGiTAL WiNG'}]},
 'c54e88c1-076e-4cc7-bce9-d861ada89ed2': {'AlbumID': '00016005-985e-4f11-b06d-e2f37fd65608',
  'AlbumName': 'Taste me up!',
  'Artists': [{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae',
    'name': 'DiGiTAL WiNG'}]},
 'cf588af1-8ad4-4ea4-9ca7-466a14643d92': {'AlbumID': '00016005-985e-4f11-b06d-e2f37fd65608',
  'AlbumName': 'Taste me up!',
  'Artists': [{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae',
    'name': 'DiGiTAL WiNG'}]},
 'cf72b9a9-292f-451b-8f03-c3e54304b6ea': {'AlbumID': '00016005-985e-4f11-b06d-e2f37fd65608',
  'AlbumName': 'Taste me up!',
  'Artists': [{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae',
    'name': 'DiGiTAL WiNG'}]},
 'd173f51d-fa33-4c09-aeed-91c468d5b208': {'AlbumID': '00016005-985e-4f11-b06d-e2f37fd65608',
  'AlbumName': 'Taste me up!',
  'Artists': [{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae',
    'name': 'DiGiTAL WiNG'}]},
 'd33ff253-f4f0-4f2e-80c6-c6f06fbb6ca1': {'AlbumID': '00016005-985e-4f11-b06d-e2f37fd65608',
  'AlbumName': 'Taste me up!',
  'Artists': [{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae',
    'name': 'DiGiTAL WiNG'}]},
 'f4808ffc-979c-42ea-90a4-462e82fb47eb': {'AlbumID': '00016005-985e-4f11-b06d-e2f37fd65608',
  'AlbumName': 'Taste me up!',
  'Artists': [{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae',
    'name': 'DiGiTAL WiNG'}]},
 'fadcd744-aba8-47e1-8c2c-6e3da7e6c5f9': {'AlbumID': '00016005-985e-4f11-b06d-e2f37fd65608',
  'AlbumName': 'Taste me up!',
  'Artists': [{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae',
    'name': 'DiGiTAL WiNG'}]},
 '558d16f1-dea1-461e-a000-3edd2308d377': {'AlbumID': '00019c74-d211-4f9a-8e15-1a7bca51bb1f',
  'AlbumName': 'Rebirth',
  'Artists': [{'id': '6cd927f5-808e-48b9-85db-1625a0e35114',
    'name': 'Karkan'}]},
 '5b9ca6a8-4592-4449-8273-3ae8bf98181c': {'AlbumID': '00019c74-d211-4f9a-8e15-1a7bca51bb1f',
  'AlbumName': 'Rebirth',
  'Artists': [{'id': '6cd927f5-808e-48b9-85db-1625a0e35114',
    'name': 'Karkan'}]},
 '62b266e7-0528-4569-b5cd-d3a882cd9c45': {'AlbumID': '00019c74-d211-4f9a-8e15-1a7bca51bb1f',
  'AlbumName': 'Rebirth',
  'Artists': [{'id': '6cd927f5-808e-48b9-85db-1625a0e35114',
    'name': 'Karkan'}]},
 '67f45f93-07ee-420d-8310-eac15917d5e5': {'AlbumID': '00019c74-d211-4f9a-8e15-1a7bca51bb1f',
  'AlbumName': 'Rebirth',
  'Artists': [{'id': '6cd927f5-808e-48b9-85db-1625a0e35114',
    'name': 'Karkan'}]},
 '85ac420a-f353-46ca-8f90-32fa5d3a7608': {'AlbumID': '00019c74-d211-4f9a-8e15-1a7bca51bb1f',
  'AlbumName': 'Rebirth',
  'Artists': [{'id': '6cd927f5-808e-48b9-85db-1625a0e35114',
    'name': 'Karkan'}]},
 'c5b6438f-a2ac-48db-8d72-712521546820': {'AlbumID': '00019c74-d211-4f9a-8e15-1a7bca51bb1f',
  'AlbumName': 'Rebirth',
  'Artists': [{'id': '6cd927f5-808e-48b9-85db-1625a0e35114',
    'name': 'Karkan'}]},
 'e977e41a-9b80-463a-99ba-36c65d3e08be': {'AlbumID': '00019c74-d211-4f9a-8e15-1a7bca51bb1f',
  'AlbumName': 'Rebirth',
  'Artists': [{'id': '6cd927f5-808e-48b9-85db-1625a0e35114',
    'name': 'Karkan'}]},
 'f37b05a5-b1b5-480d-996b-a30792bdf17c': {'AlbumID': '00019c74-d211-4f9a-8e15-1a7bca51bb1f',
  'AlbumName': 'Rebirth',
  'Artists': [{'id': '6cd927f5-808e-48b9-85db-1625a0e35114',
    'name': 'Karkan'}]},
 'fedb5022-576f-4cf3-a82d-4274ff6fffed': {'AlbumID': '00019c74-d211-4f9a-8e15-1a7bca51bb1f',
  'AlbumName': 'Rebirth',
  'Artists': [{'id': '6cd927f5-808e-48b9-85db-1625a0e35114',
    'name': 'Karkan'}]},
 '4abda64d-26f9-41c7-bc3c-e04451ce0828': {'AlbumID': '0003710d-0225-4f4b-8473-64c0bb4f5aa7',
  'AlbumName': 'Cinematic Disc Instrumental',
  'Artists': [{'id': '7725a3ee-3a92-4eb6-b5cd-b5461d402e89',
    'name': 'Halozy'}]},
 '4b1d1d4e-1e17-411f-a227-4c5857267875': {'AlbumID': '0003710d-0225-4f4b-8473-64c0bb4f5aa7',
  'AlbumName': 'Cinematic Disc Instrumental',
  'Artists': [{'id': '7725a3ee-3a92-4eb6-b5cd-b5461d402e89',
    'name': 'Halozy'}]},
 '574bab53-8b10-4585-80e0-11cb447b3090': {'AlbumID': '0003710d-0225-4f4b-8473-64c0bb4f5aa7',
  'AlbumName': 'Cinematic Disc Instrumental',
  'Artists': [{'id': '7725a3ee-3a92-4eb6-b5cd-b5461d402e89',
    'name': 'Halozy'}]},
 '87bdccb7-499f-4657-afaf-3cd1709dface': {'AlbumID': '0003710d-0225-4f4b-8473-64c0bb4f5aa7',
  'AlbumName': 'Cinematic Disc Instrumental',
  'Artists': [{'id': '7725a3ee-3a92-4eb6-b5cd-b5461d402e89',
    'name': 'Halozy'}]},
 '8b2174e7-e14b-4737-a5ae-e25dc3f116a1': {'AlbumID': '0003710d-0225-4f4b-8473-64c0bb4f5aa7',
  'AlbumName': 'Cinematic Disc Instrumental',
  'Artists': [{'id': '7725a3ee-3a92-4eb6-b5cd-b5461d402e89',
    'name': 'Halozy'}]},
 '95f3b295-fd58-4ee9-92b2-3a244071988c': {'AlbumID': '0003710d-0225-4f4b-8473-64c0bb4f5aa7',
  'AlbumName': 'Cinematic Disc Instrumental',
  'Artists': [{'id': '7725a3ee-3a92-4eb6-b5cd-b5461d402e89',
    'name': 'Halozy'}]},
 'a63a23b7-863a-49e4-a7f4-5be3326aaae3': {'AlbumID': '0003710d-0225-4f4b-8473-64c0bb4f5aa7',
  'AlbumName': 'Cinematic Disc Instrumental',
  'Artists': [{'id': '7725a3ee-3a92-4eb6-b5cd-b5461d402e89',
    'name': 'Halozy'}]},
 'af068d08-5e2d-4ded-9e3c-d6c53bd2225e': {'AlbumID': '0003710d-0225-4f4b-8473-64c0bb4f5aa7',
  'AlbumName': 'Cinematic Disc Instrumental',
  'Artists': [{'id': '7725a3ee-3a92-4eb6-b5cd-b5461d402e89',
    'name': 'Halozy'}]},
 'cef084e0-6de2-4a9f-a44a-c48d97b72f15': {'AlbumID': '0003710d-0225-4f4b-8473-64c0bb4f5aa7',
  'AlbumName': 'Cinematic Disc Instrumental',
  'Artists': [{'id': '7725a3ee-3a92-4eb6-b5cd-b5461d402e89',
    'name': 'Halozy'}]},
 'f290719c-3df8-4982-a232-70f3522eb512': {'AlbumID': '0003710d-0225-4f4b-8473-64c0bb4f5aa7',
  'AlbumName': 'Cinematic Disc Instrumental',
  'Artists': [{'id': '7725a3ee-3a92-4eb6-b5cd-b5461d402e89',
    'name': 'Halozy'}]},
 '1394406d-1174-40af-bf53-459d637db3d6': {'AlbumID': '00046fec-fa93-4bf3-bc31-2cfe267bed78',
  'AlbumName': '転生したら剣でした',
  'Artists': [{'id': 'faa689b4-b345-4e0d-be19-066eebf55a56',
    'name': '岸田教団&THE明星ロケッツ'}]},
 '1aa164fd-0c2b-409f-b2a7-55ed6482b55b': {'AlbumID': '00046fec-fa93-4bf3-bc31-2cfe267bed78',
  'AlbumName': '転生したら剣でした',
  'Artists': [{'id': 'faa689b4-b345-4e0d-be19-066eebf55a56',
    'name': '岸田教団&THE明星ロケッツ'}]},
 '3b283138-bad8-4438-bb2c-19266728bc16': {'AlbumID': '00046fec-fa93-4bf3-bc31-2cfe267bed78',
  'AlbumName': '転生したら剣でした',
  'Artists': [{'id': 'faa689b4-b345-4e0d-be19-066eebf55a56',
    'name': '岸田教団&THE明星ロケッツ'}]},
 '5b0d9b6b-8f3f-4d07-99c3-fefff9feb91d': {'AlbumID': '00046fec-fa93-4bf3-bc31-2cfe267bed78',
  'AlbumName': '転生したら剣でした',
  'Artists': [{'id': 'faa689b4-b345-4e0d-be19-066eebf55a56',
    'name': '岸田教団&THE明星ロケッツ'}]},
 'b7ef83b7-aa7e-4aa8-8201-9fab3cb8a2e8': {'AlbumID': '00046fec-fa93-4bf3-bc31-2cfe267bed78',
  'AlbumName': '転生したら剣でした',
  'Artists': [{'id': 'faa689b4-b345-4e0d-be19-066eebf55a56',
    'name': '岸田教団&THE明星ロケッツ'}]},
 '20ddf75c-7bfe-43af-aeab-d1dca2e45364': {'AlbumID': '00053d74-aa78-4abe-9a65-1c8512b97ca2',
  'AlbumName': '竹山風 参',
  'Artists': [{'id': 'a6065265-6413-4541-bc7e-e7f466666dd0',
    'name': 'nekomimi style'}]},
 '32759cb1-e549-4fc0-9426-d681232d613f': {'AlbumID': '00053d74-aa78-4abe-9a65-1c8512b97ca2',
  'AlbumName': '竹山風 参',
  'Artists': [{'id': 'a6065265-6413-4541-bc7e-e7f466666dd0',
    'name': 'nekomimi style'}]},
 '8daadb15-41b2-4e13-a311-67fdd9d1d401': {'AlbumID': '00053d74-aa78-4abe-9a65-1c8512b97ca2',
  'AlbumName': '竹山風 参',
  'Artists': [{'id': 'a6065265-6413-4541-bc7e-e7f466666dd0',
    'name': 'nekomimi style'}]},
 '9fc822d3-407f-4ebd-a88c-741855a34586': {'AlbumID': '00053d74-aa78-4abe-9a65-1c8512b97ca2',
  'AlbumName': '竹山風 参',
  'Artists': [{'id': 'a6065265-6413-4541-bc7e-e7f466666dd0',
    'name': 'nekomimi style'}]},
 'b70544a3-a6d5-4a82-8a93-e734371d9d7a': {'AlbumID': '00053d74-aa78-4abe-9a65-1c8512b97ca2',
  'AlbumName': '竹山風 参',
  'Artists': [{'id': 'a6065265-6413-4541-bc7e-e7f466666dd0',
    'name': 'nekomimi style'}]},
 'be0d1b87-1977-4c50-9523-1bff931adc2e': {'AlbumID': '00053d74-aa78-4abe-9a65-1c8512b97ca2',
  'AlbumName': '竹山風 参',
  'Artists': [{'id': 'a6065265-6413-4541-bc7e-e7f466666dd0',
    'name': 'nekomimi style'}]},
 'd3e1d7e9-1e86-4c62-baeb-deb8044e2229': {'AlbumID': '00053d74-aa78-4abe-9a65-1c8512b97ca2',
  'AlbumName': '竹山風 参',
  'Artists': [{'id': 'a6065265-6413-4541-bc7e-e7f466666dd0',
    'name': 'nekomimi style'}]},
 'd59246f4-4a81-4060-ada6-43a32e7e5d9b': {'AlbumID': '00053d74-aa78-4abe-9a65-1c8512b97ca2',
  'AlbumName': '竹山風 参',
  'Artists': [{'id': 'a6065265-6413-4541-bc7e-e7f466666dd0',
    'name': 'nekomimi style'}]},
 'd8d9d9d7-3faa-476e-9b2c-089e85d930c6': {'AlbumID': '00053d74-aa78-4abe-9a65-1c8512b97ca2',
  'AlbumName': '竹山風 参',
  'Artists': [{'id': 'a6065265-6413-4541-bc7e-e7f466666dd0',
    'name': 'nekomimi style'}]},
 'f52d23c4-ec6f-42a0-a186-46e69b7ceb93': {'AlbumID': '00053d74-aa78-4abe-9a65-1c8512b97ca2',
  'AlbumName': '竹山風 参',
  'Artists': [{'id': 'a6065265-6413-4541-bc7e-e7f466666dd0',
    'name': 'nekomimi style'}]},
 '0d95a570-8de5-416c-bde4-a9db29e5bc7e': {'AlbumID': '000722f5-1590-4aaf-9d4c-4f3219fe0a34',
  'AlbumName': 'AD:HOUSE 5',
  'Artists': [{'id': '2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a',
    'name': 'Diverse System'}]},
 '1d4c0580-8029-47b8-acec-00bcf1bfac18': {'AlbumID': '000722f5-1590-4aaf-9d4c-4f3219fe0a34',
  'AlbumName': 'AD:HOUSE 5',
  'Artists': [{'id': '2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a',
    'name': 'Diverse System'}]},
 '26ae3845-9b39-433e-85b8-9a31f4b9c963': {'AlbumID': '000722f5-1590-4aaf-9d4c-4f3219fe0a34',
  'AlbumName': 'AD:HOUSE 5',
  'Artists': [{'id': '2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a',
    'name': 'Diverse System'}]},
 '2b4edfd8-7b91-4a78-8bad-e178857c3865': {'AlbumID': '000722f5-1590-4aaf-9d4c-4f3219fe0a34',
  'AlbumName': 'AD:HOUSE 5',
  'Artists': [{'id': '2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a',
    'name': 'Diverse System'}]},
 '37b9cdba-d24d-4056-a081-c7374ef5841f': {'AlbumID': '000722f5-1590-4aaf-9d4c-4f3219fe0a34',
  'AlbumName': 'AD:HOUSE 5',
  'Artists': [{'id': '2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a',
    'name': 'Diverse System'}]},
 '58426d79-b837-4519-9f7a-de68e4843459': {'AlbumID': '000722f5-1590-4aaf-9d4c-4f3219fe0a34',
  'AlbumName': 'AD:HOUSE 5',
  'Artists': [{'id': '2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a',
    'name': 'Diverse System'}]},
 '635d2598-cb1f-4abf-b196-e461fd7ca5c6': {'AlbumID': '000722f5-1590-4aaf-9d4c-4f3219fe0a34',
  'AlbumName': 'AD:HOUSE 5',
  'Artists': [{'id': '2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a',
    'name': 'Diverse System'}]},
 '67d2cfd4-af71-470a-a7d4-6298111ead52': {'AlbumID': '000722f5-1590-4aaf-9d4c-4f3219fe0a34',
  'AlbumName': 'AD:HOUSE 5',
  'Artists': [{'id': '2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a',
    'name': 'Diverse System'}]},
 '70825a0c-4d55-4790-b3f6-befea9c3714e': {'AlbumID': '000722f5-1590-4aaf-9d4c-4f3219fe0a34',
  'AlbumName': 'AD:HOUSE 5',
  'Artists': [{'id': '2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a',
    'name': 'Diverse System'}]},
 '805604dd-2823-4f2f-b811-bbafcfd5884b': {'AlbumID': '000722f5-1590-4aaf-9d4c-4f3219fe0a34',
  'AlbumName': 'AD:HOUSE 5',
  'Artists': [{'id': '2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a',
    'name': 'Diverse System'}]},
 'fb69c0c0-e9c6-4744-8ad0-7b75b3f071c2': {'AlbumID': '000722f5-1590-4aaf-9d4c-4f3219fe0a34',
  'AlbumName': 'AD:HOUSE 5',
  'Artists': [{'id': '2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a',
    'name': 'Diverse System'}]},
 '98194474-f2a6-4f34-a843-8b385d18d60a': {'AlbumID': '000e34e6-1455-44a2-96a8-dad9fab37caf',
  'AlbumName': '東方M-1ぐらんぷり コンプリート音楽集',
  'Artists': [{'id': '58bde06a-2f95-4938-bf46-f7d8bbb8383e',
    'name': 'R-note'}]},
 '0b45a6e6-6bfa-4459-befe-7c7031ee8770': {'AlbumID': '000ed4bc-511c-47c8-ba43-4f47cedd22ba',
  'AlbumName': '東方ボーカルアレンジアルバム サード・インパクト',
  'Artists': [{'id': '5889af12-024d-4aa8-8471-c3897643c1a1',
    'name': 'TATAMI STUGIWO'}]},
 '4aef4c76-e32c-4449-9994-bd2326d2a0e0': {'AlbumID': '000ed4bc-511c-47c8-ba43-4f47cedd22ba',
  'AlbumName': '東方ボーカルアレンジアルバム サード・インパクト',
  'Artists': [{'id': '5889af12-024d-4aa8-8471-c3897643c1a1',
    'name': 'TATAMI STUGIWO'}]},
 '525dbb74-37c4-4444-b503-6e80f965638a': {'AlbumID': '000ed4bc-511c-47c8-ba43-4f47cedd22ba',
  'AlbumName': '東方ボーカルアレンジアルバム サード・インパクト',
  'Artists': [{'id': '5889af12-024d-4aa8-8471-c3897643c1a1',
    'name': 'TATAMI STUGIWO'}]},
 '611d07d9-8cce-4bc2-8824-a315b6409251': {'AlbumID': '000ed4bc-511c-47c8-ba43-4f47cedd22ba',
  'AlbumName': '東方ボーカルアレンジアルバム サード・インパクト',
  'Artists': [{'id': '5889af12-024d-4aa8-8471-c3897643c1a1',
    'name': 'TATAMI STUGIWO'}]},
 '79604a51-1f5a-4fe4-94f1-e7023cd6f100': {'AlbumID': '000ed4bc-511c-47c8-ba43-4f47cedd22ba',
  'AlbumName': '東方ボーカルアレンジアルバム サード・インパクト',
  'Artists': [{'id': '5889af12-024d-4aa8-8471-c3897643c1a1',
    'name': 'TATAMI STUGIWO'}]},
 '7fd7ab19-aacc-43f6-9951-39a0c8b7f66f': {'AlbumID': '000ed4bc-511c-47c8-ba43-4f47cedd22ba',
  'AlbumName': '東方ボーカルアレンジアルバム サード・インパクト',
  'Artists': [{'id': '5889af12-024d-4aa8-8471-c3897643c1a1',
    'name': 'TATAMI STUGIWO'}]},
 '8abbe28e-3a98-4907-ab13-2f7eb91f90c7': {'AlbumID': '000ed4bc-511c-47c8-ba43-4f47cedd22ba',
  'AlbumName': '東方ボーカルアレンジアルバム サード・インパクト',
  'Artists': [{'id': '5889af12-024d-4aa8-8471-c3897643c1a1',
    'name': 'TATAMI STUGIWO'}]},
 '922eda50-151e-4e16-a7ac-005561744803': {'AlbumID': '000ed4bc-511c-47c8-ba43-4f47cedd22ba',
  'AlbumName': '東方ボーカルアレンジアルバム サード・インパクト',
  'Artists': [{'id': '5889af12-024d-4aa8-8471-c3897643c1a1',
    'name': 'TATAMI STUGIWO'}]},
 'a45d93d1-4cf1-44ed-aaed-f0ff851cb437': {'AlbumID': '000ed4bc-511c-47c8-ba43-4f47cedd22ba',
  'AlbumName': '東方ボーカルアレンジアルバム サード・インパクト',
  'Artists': [{'id': '5889af12-024d-4aa8-8471-c3897643c1a1',
    'name': 'TATAMI STUGIWO'}]},
 '0565a847-99a8-40ff-9ad3-ce136f1c7ec2': {'AlbumID': '002c7454-2d29-4737-b129-62c648da4eb2',
  'AlbumName': 'Shinen',
  'Artists': [{'id': 'fd7ab46d-4205-4e15-a9d9-64a2a1d9696b',
    'name': 'Glassy：oceaN'}]},
 '25442fec-c343-4c7e-a895-f141736c1569': {'AlbumID': '002c7454-2d29-4737-b129-62c648da4eb2',
  'AlbumName': 'Shinen',
  'Artists': [{'id': 'fd7ab46d-4205-4e15-a9d9-64a2a1d9696b',
    'name': 'Glassy：oceaN'}]},
 '2d2df3ad-63c3-4d46-9985-dcda413710e7': {'AlbumID': '002c7454-2d29-4737-b129-62c648da4eb2',
  'AlbumName': 'Shinen',
  'Artists': [{'id': 'fd7ab46d-4205-4e15-a9d9-64a2a1d9696b',
    'name': 'Glassy：oceaN'}]},
 'ae437248-3963-45c3-abbb-c5370541a13b': {'AlbumID': '002c7454-2d29-4737-b129-62c648da4eb2',
  'AlbumName': 'Shinen',
  'Artists': [{'id': 'fd7ab46d-4205-4e15-a9d9-64a2a1d9696b',
    'name': 'Glassy：oceaN'}]},
 'f3057dad-8acb-4672-a860-0988d900f937': {'AlbumID': '002c7454-2d29-4737-b129-62c648da4eb2',
  'AlbumName': 'Shinen',
  'Artists': [{'id': 'fd7ab46d-4205-4e15-a9d9-64a2a1d9696b',
    'name': 'Glassy：oceaN'}]},
 '10cd10f6-46ef-4338-a14c-0cab07030bd3': {'AlbumID': '002d17d8-7f63-4385-b65b-9cc071ed4e0d',
  'AlbumName': '東方幻想甘露譚 Vol2 七色の魔法使いにナース服で甘く看病される一日',
  'Artists': [{'id': 'ca0e5dcc-3257-4043-8478-fe89a964ae45',
    'name': 'ガムシロコーラ'}]},
 '38cbea63-91ab-4a80-acb6-aea34e6fcebe': {'AlbumID': '002d17d8-7f63-4385-b65b-9cc071ed4e0d',
  'AlbumName': '東方幻想甘露譚 Vol2 七色の魔法使いにナース服で甘く看病される一日',
  'Artists': [{'id': 'ca0e5dcc-3257-4043-8478-fe89a964ae45',
    'name': 'ガムシロコーラ'}]},
 'ae2b145c-df49-44d9-b233-0e2ccb2e58f0': {'AlbumID': '002d17d8-7f63-4385-b65b-9cc071ed4e0d',
  'AlbumName': '東方幻想甘露譚 Vol2 七色の魔法使いにナース服で甘く看病される一日',
  'Artists': [{'id': 'ca0e5dcc-3257-4043-8478-fe89a964ae45',
    'name': 'ガムシロコーラ'}]},
 'bb97bc6e-001d-41ac-b5ad-6fbeb9bd19d0': {'AlbumID': '002d17d8-7f63-4385-b65b-9cc071ed4e0d',
  'AlbumName': '東方幻想甘露譚 Vol2 七色の魔法使いにナース服で甘く看病される一日',
  'Artists': [{'id': 'ca0e5dcc-3257-4043-8478-fe89a964ae45',
    'name': 'ガムシロコーラ'}]},
 'f4627501-e16d-4701-9ef6-4e0571f4dc93': {'AlbumID': '002d17d8-7f63-4385-b65b-9cc071ed4e0d',
  'AlbumName': '東方幻想甘露譚 Vol2 七色の魔法使いにナース服で甘く看病される一日',
  'Artists': [{'id': 'ca0e5dcc-3257-4043-8478-fe89a964ae45',
    'name': 'ガムシロコーラ'}]},
 '5d7d5cf2-d200-42ad-a126-c812e97767ee': {'AlbumID': '002fb991-1db1-44e6-a910-1983b7fc66f1',
  'AlbumName': 'SPECIAL UNDERGROUND POPS',
  'Artists': [{'id': '274858c2-7e1b-4b5f-8d0b-6e2dc378c787',
    'name': 'さよならレコード'}]},
 '7a2f4f08-b8c6-457b-8dda-6358c4513f0d': {'AlbumID': '002fb991-1db1-44e6-a910-1983b7fc66f1',
  'AlbumName': 'SPECIAL UNDERGROUND POPS',
  'Artists': [{'id': '274858c2-7e1b-4b5f-8d0b-6e2dc378c787',
    'name': 'さよならレコード'}]},
 '9b0e7310-0677-4770-a0f9-c0abd9deb6b1': {'AlbumID': '002fb991-1db1-44e6-a910-1983b7fc66f1',
  'AlbumName': 'SPECIAL UNDERGROUND POPS',
  'Artists': [{'id': '274858c2-7e1b-4b5f-8d0b-6e2dc378c787',
    'name': 'さよならレコード'}]},
 'bc2266a1-6e8c-49fc-888a-96ee81633b1b': {'AlbumID': '002fb991-1db1-44e6-a910-1983b7fc66f1',
  'AlbumName': 'SPECIAL UNDERGROUND POPS',
  'Artists': [{'id': '274858c2-7e1b-4b5f-8d0b-6e2dc378c787',
    'name': 'さよならレコード'}]},
 'c0dc92b9-709e-4d0e-b7da-04896655da34': {'AlbumID': '002fb991-1db1-44e6-a910-1983b7fc66f1',
  'AlbumName': 'SPECIAL UNDERGROUND POPS',
  'Artists': [{'id': '274858c2-7e1b-4b5f-8d0b-6e2dc378c787',
    'name': 'さよならレコード'}]},
 'd3d8dd57-17dd-4291-af0a-df4b5144eb33': {'AlbumID': '002fb991-1db1-44e6-a910-1983b7fc66f1',
  'AlbumName': 'SPECIAL UNDERGROUND POPS',
  'Artists': [{'id': '274858c2-7e1b-4b5f-8d0b-6e2dc378c787',
    'name': 'さよならレコード'}]},
 '11969b07-ad7d-43e3-9113-00a40f392981': {'AlbumID': '0038ecfb-807d-49ed-87f6-e73dd7391ea3',
  'AlbumName': '東方エボリューション',
  'Artists': [{'id': 'e0c4510a-90ec-4932-a3c4-3bb511a00aa3',
    'name': 'RedGear'}]},
 '30e83ad8-dc67-4d5d-a8ae-efe6d351f82f': {'AlbumID': '0038ecfb-807d-49ed-87f6-e73dd7391ea3',
  'AlbumName': '東方エボリューション',
  'Artists': [{'id': 'e0c4510a-90ec-4932-a3c4-3bb511a00aa3',
    'name': 'RedGear'}]},
 '3f0f4c35-716a-4d7a-8e22-857518bf980a': {'AlbumID': '0038ecfb-807d-49ed-87f6-e73dd7391ea3',
  'AlbumName': '東方エボリューション',
  'Artists': [{'id': 'e0c4510a-90ec-4932-a3c4-3bb511a00aa3',
    'name': 'RedGear'}]},
 '4b4b0859-4a0d-4a30-ab8a-e6db1d198e5d': {'AlbumID': '0038ecfb-807d-49ed-87f6-e73dd7391ea3',
  'AlbumName': '東方エボリューション',
  'Artists': [{'id': 'e0c4510a-90ec-4932-a3c4-3bb511a00aa3',
    'name': 'RedGear'}]},
 '59333c87-867d-4b56-9957-73eb32e0543a': {'AlbumID': '0038ecfb-807d-49ed-87f6-e73dd7391ea3',
  'AlbumName': '東方エボリューション',
  'Artists': [{'id': 'e0c4510a-90ec-4932-a3c4-3bb511a00aa3',
    'name': 'RedGear'}]},
 '8a8eb85d-567f-4b5e-bba4-163157f07468': {'AlbumID': '0038ecfb-807d-49ed-87f6-e73dd7391ea3',
  'AlbumName': '東方エボリューション',
  'Artists': [{'id': 'e0c4510a-90ec-4932-a3c4-3bb511a00aa3',
    'name': 'RedGear'}]},
 'b602c864-74ce-4595-9653-8184d586a4a1': {'AlbumID': '0038ecfb-807d-49ed-87f6-e73dd7391ea3',
  'AlbumName': '東方エボリューション',
  'Artists': [{'id': 'e0c4510a-90ec-4932-a3c4-3bb511a00aa3',
    'name': 'RedGear'}]},
 'd7a0e100-0a2a-4758-b098-81615b04b7ad': {'AlbumID': '0038ecfb-807d-49ed-87f6-e73dd7391ea3',
  'AlbumName': '東方エボリューション',
  'Artists': [{'id': 'e0c4510a-90ec-4932-a3c4-3bb511a00aa3',
    'name': 'RedGear'}]},
 '012822ee-b7b1-477c-abe4-dddda0c3e6f0': {'AlbumID': '003b6dfe-a0b3-4ebb-839d-d02492a8d65d',
  'AlbumName': '洩矢諏訪子ワークス「みしゃくじカタルシス」',
  'Artists': [{'id': 'dc84e236-015d-495f-a8b2-1e2e8db3fd5d',
    'name': 'ビターショコラ抹茶ラテ'}]},
 '16d778d2-bc2a-4efa-b019-29615607bbff': {'AlbumID': '003b6dfe-a0b3-4ebb-839d-d02492a8d65d',
  'AlbumName': '洩矢諏訪子ワークス「みしゃくじカタルシス」',
  'Artists': [{'id': 'dc84e236-015d-495f-a8b2-1e2e8db3fd5d',

In [ ]:
# compute index of tensor to track id
from typing import Dict

missing_keys: Dict[str, int] = {}
for idx, key in enumerate(tensors.keys()):
  uuid = key.split(".")[0]
  try:
    metadata_dict[uuid]["TensorIdx"] = idx
  except:
    missing_keys[uuid] = idx

print(f"Missing keys: {missing_keys}, diff: {len(missing_keys)}")

Missing keys: {'0111e11f-2e2b-4ff1-8d7c-be6c45ea1b2c': 586, '015b8712-c2de-4a8f-baa0-b8b5d02155e3': 732, '01e86b65-6348-4bc9-af30-fd580d905919': 1051, '0320e638-0f54-41f6-8b6f-1ea22b160ddc': 1689, '038b889d-9bd4-4d7d-ba11-95ac87b9ef86': 1899, '041e2616-6b48-4548-b4c5-c216953ca998': 2195, '0436a26a-6c3a-4100-afee-e028ec246e3c': 2247, '04b688bf-0327-4235-8f5a-bcaf3c9defbd': 2517, '0578de3d-1e2d-4368-9480-806c21ceeb47': 2937, '06012c8f-8f50-41b2-9a35-858b66db8b14': 3237, '063e2725-8d30-4496-b1f0-acd84da40c15': 3372, '07c3cb30-654f-4269-a005-de1087d34d40': 4198, '0916c1bc-42e6-4c48-84f6-8cdc68cac18c': 4931, '091f98ca-5948-4102-9018-64e48c8bc25c': 4950, '0a32c882-c217-4872-b2ec-cd8a5b12ec78': 5503, '0a5027ab-45e3-4f11-a08e-f17c12c1aac1': 5562, '0cc6e0a2-7365-4151-8a04-bae20f553df4': 6866, '0d8dd2dd-3b22-4435-947e-b3624c33ca07': 7294, '0e2072b0-a591-484d-a306-40ddc0bc46ff': 7598, '100bbf91-3f2a-4acb-86fc-6de39d1e7089': 8615, '119b2540-9268-45ce-bce1-c9300ba24130': 9438, '12227217-6cb3-421b-8f81-b2cd144b7bfa': 9714, '126ff41a-2f17-4eb4-b650-f54b12a73ef2': 9889, '12b7a3ac-ad4c-4019-909b-616a0154b343': 10043, '12fa7d84-fb0f-47c4-a675-afe8fde9dd5b': 10192, '141cbe14-9823-4203-9764-034c6b286c33': 10834, '14abac8f-ff3e-4c32-976a-698d9ea8c32a': 11126, '14c5fc3f-a583-48eb-a35f-d14d4f405aea': 11181, '15e95a13-d1b2-4400-8f4a-d9b184453bc2': 11831, '16bda71f-f60e-43fa-8d6f-5d622148f50a': 12292, '1ae74b1f-45f9-483c-9d99-9c6c1d3ccf34': 14553, '1bc0e12b-03ee-48f2-a96a-c47f0d9bc84c': 15014, '1df516a8-e878-4459-b8ba-fc94b085a51e': 16246, '1eb7d3f3-231a-495b-b555-2538aca5668e': 16663, '1f3793a5-d33d-4c6b-88d1-9b17ee050c68': 16949, '2086e550-2199-4554-bafa-785f5b74a835': 17608, '20b9eceb-7698-46f6-963e-48ec0ca9fc6c': 17721, '24211c6e-4b19-44fb-be45-f00063a97d38': 19619, '2467650f-93f4-46f8-af62-bb2643c9f396': 19766, '24f85da7-88da-4c8f-91af-b64a6125207b': 20040, '252d0216-2e61-48bc-82e1-3ecc54c5e722': 20161, '26ace000-8847-4bb5-971f-e886c9c0855e': 20968, '2721a4b6-7adb-482d-bed4-01f338ed95e0': 21206, '2817ab06-2fa5-4ce2-a960-b6b097ff563b': 21707, '285ce2e2-abd3-4632-b15b-292067dcf8d2': 21841, '292986ed-4739-40da-a4a0-def79ec4d028': 22270, '298dc37e-b119-4b65-928b-664248acab1c': 22462, '2a212155-b66e-434a-9326-7ddbc6e566fc': 22784, '2a304ce3-cc04-4dc2-8dca-60ee5b96c3d4': 22834, '2b3c69ff-21ce-4745-be72-916b25ffb905': 23405, '2c00676d-5144-4771-95d0-2d98ae994dd5': 23823, '2c347a6d-78cd-44d1-9098-41e16f0154aa': 23944, '2d119b25-43e7-41a0-9886-7c8aade61d45': 24414, '2d76a1e6-eb94-4cea-84c9-8783f88442a3': 24629, '2e00c89a-02be-4431-a953-dd985b96fbeb': 24907, '2f24cd9c-40a4-4581-a0bd-2639b697a2ea': 25489, '31122f72-bbf3-4289-bfcd-8ccd598fa4b3': 26556, '314ba8f8-5029-4c43-a02f-9ec71050d630': 26649, '337e80fd-29ff-4d4f-98fa-0c683d249a48': 27827, '3442217e-b3fd-4f2a-9fcf-14b9a835b02f': 28265, '34a261bf-628f-422e-a6ab-16081e831eb8': 28436, '3572ae14-b072-451f-a8f0-7d0db722d77d': 28871, '357d2268-17bf-4be3-bb88-c88c872df544': 28896, '358d3b61-50b0-4440-ae16-c9a8c75f9e7a': 28926, '368790ee-b397-40a5-9335-53ef592ba23d': 29460, '368cc1d0-c8f4-4cb2-a276-39309de3e673': 29475, '372208cf-ee99-41ff-8f17-747abd208131': 29797, '379d6b8a-c426-40b8-94ef-d5a13f1de95f': 30033, '37ac46f8-e3b7-4d6f-bbe4-f9562032fced': 30061, '37f35098-5ef1-478d-b269-c24185180625': 30232, '383fa98d-a797-4216-9717-0cd0c9396df2': 30404, '3901b074-c807-44f1-a8af-dfc9c6aa1e75': 30797, '39512f8c-07c9-4e9e-88bf-4f22008cccc9': 30978, '398ae24a-5f64-4cf2-8ff7-d3040cda66fd': 31116, '3b23dbb0-4616-4338-99be-92a7fd2ebee1': 31959, '3b63a02a-e100-4677-aee2-d89cd1453d48': 32077, '3b8789a3-0ee5-431b-8b01-de046c3335d0': 32165, '3dcd9015-3650-41a9-9ab8-15fb74125934': 33388, '3f1b682c-6dac-42e7-a363-76db94225e08': 34077, '3f88592d-edca-44cb-9333-b14b72c7f64e': 34301, '3fb6a269-d158-4cdb-9ab8-aae0ce59551c': 34403, '3fe56dab-d5e5-4acd-a701-a710619dfc2c': 34492, '40a3b118-23b3-4e65-aa41-c88ffba4d5c0': 34920, '414914ae-29c0-444e-9c81-307c94da0ead': 35255, '43bea140-5a11-4e7c-835a-06ac0f0cdde4': 36670, '43efd100-8b72-451e-a3be-6ac97687a056': 36778, '44a2ca01-17d1-4dae-be65-04c6804694f8': 37151, '46faa38a-fd19-4936-87c6-9219efc489a4': 38332, '4716898d-0e41-43f4-ab61-92a66a6beef5': 38386, '4738ce58-d740-4f2e-b19f-00fb19899359': 38451, '479ab5e8-f56c-4dc6-a75b-a4a4efd7f3e5': 38669, '487b704c-7f2a-44ee-9c9a-99d29391654e': 39162, '490458bd-41c2-4a09-bcd7-0db27806aede': 39451, '49138c86-3509-4b1e-8d3e-4bdd1800b9a5': 39482, '4949d00b-aaae-4635-9ec0-ee033c7baba7': 39590, '4a469ea0-f218-43bb-ba7d-0c750ac90b8c': 40153, '4d5d33f5-2460-4e2e-b49b-a0f5a74a122a': 41856, '4e72c0a4-fbbd-4226-be16-f395d888246a': 42427, '4f040670-fe17-469f-975f-b4ee98106663': 42724, '514023d4-3e8b-4687-9de0-b6d5b0d96fca': 43928, '5142e347-f3f2-417c-9e1f-00dda3ff6582': 43936, '51669104-a74b-46fe-a92c-f6bff4ed9aac': 44011, '51f9f5dd-677e-4491-9625-3370c0119ba8': 44311, '540017b8-a2ac-4e8a-b428-3f58ac8055d5': 45395, '54268cbb-09f0-49d0-960c-22526222f828': 45477, '5447eb98-8b90-435a-b460-ea1b9663ba9e': 45554, '553d161d-778d-469d-b77e-6513ae24f40e': 46077, '55a1ee99-543f-4f2b-bf26-cede82023d72': 46278, '55a47603-f097-4ba9-a641-f79dea388b2a': 46284, '561d6e50-52be-40ad-a428-a2ecd0b63f30': 46514, '5aaab770-80a7-4aca-afcf-4bdd137ed0a2': 48988, '5c0a3f3d-9cb7-4a9d-a8f6-2355e2503542': 49719, '5c303b8b-55a7-40e4-aea1-ca2ee9041d5b': 49820, '5c38ddb3-f523-4600-8300-703d5fb196e9': 49834, '5cb6fbec-ab17-4e6c-a2d9-52e455ceca77': 50112, '5cfc4201-fc52-4f58-a18a-65912f2f8a72': 50262, '5dc2cf46-ba56-4e9c-a24e-a10553dac8d8': 50699, '5df33902-b66d-4c89-a574-ad03100fe9be': 50793, '5ea02b36-976c-4760-b32b-48e8ac9acc79': 51144, '5f12d18c-eed7-4dac-ac1c-5b7229c7f66f': 51401, '5f7870d0-d94c-4b3d-8602-ff61c06afe33': 51636, '619ccc53-71ac-4869-8560-be65ee04afa6': 52767, '61acec83-fad7-4847-aed3-f415369fe1d8': 52806, '62b620e8-f92a-4330-a5e6-be75f14b3d98': 53375, '62d01932-187f-4e4f-bc37-83276f2eaf07': 53433, '62ffc6a6-1c3f-4f11-9e82-d268d85d87c9': 53548, '6359920b-cd3c-453d-8b4f-e2afe49af7f2': 53756, '63dbbc9d-7095-4130-879f-be77dd739f99': 54003, '63fa4c68-755f-488a-8101-9d26ed97d25d': 54063, '64392087-0367-43d1-9d69-149a975eb338': 54182, '652d7a7e-102e-424f-bf2a-4e6c3e79438d': 54704, '670b9d24-2f96-4a45-9f6c-d8d19eea8b92': 55657, '67a1be3e-8ea0-47e3-a9d3-732c27f2fe60': 55970, '67d73a58-a141-4a7b-a232-92daac871f18': 56098, '681d5d95-2367-4484-b578-cac8a81c26f2': 56254, '68b2623f-f858-4eb2-b947-d76bc4cccf46': 56562, '68b4558a-3b22-42c3-8a44-1411cf1db5f5': 56565, '68be0b26-3477-4379-b7c6-cdda15ad8789': 56582, '693c3933-f671-4710-bd95-821e5a8750d7': 56849, '6958f011-1a14-4a0b-8d0f-14be9b73d6eb': 56909, '696c4555-3162-4680-9907-6dd4dd07ac52': 56956, '69a559b2-dc73-43a7-91bf-27555108b273': 57087, '6a20d53d-1cda-41ad-8796-7101fe00cb6f': 57347, '6aa71cdf-2217-4f97-b29f-b6eb0296c7c4': 57626, '6b1867d1-1643-4e7b-ac87-aa458d24d116': 57880, '6b61caa5-7589-4f33-a409-f98d8ef3c974': 58051, '6c8ccd3e-32e1-498b-8d20-e86b3dc13b68': 58714, '6ca646cc-b490-442c-8d1d-4f5dd518d634': 58763, '6dad35de-cb7c-444a-af08-8cf498f08f24': 59297, '6dfabd84-41d5-4a9d-8d2d-4fbb1d2ed478': 59465, '6e287561-bb3d-4054-b91e-3af1a732a5d1': 59576, '6e8ef299-fb29-460d-a6f0-70420dfdc989': 59804, '6f858279-c96f-4386-9700-16e27250fc85': 60336, '6fc03712-ad6e-470e-b9e6-add879c5034e': 60468, '7093f1d2-d6b0-4164-8b15-dc45d8563c11': 60909, '71524be8-3d3f-437b-affb-6651600cb0dd': 61323, '7357c637-eb84-4de1-b093-d6fd31dba6cb': 62397, '757264b2-1c69-4b88-9f93-7f91286fc7ba': 63472, '75bdd6ec-2472-417b-9bed-569bd61aa103': 63635, '76be9754-93b3-45b4-a468-54b54e260848': 64107, '78245beb-b93d-4a2c-89f8-22645c4df2d4': 64838, '78ea6db9-3b88-4aa2-b1a0-912ea0b4b60b': 65261, '797137cf-9fee-415f-a787-d363d505ff48': 65546, '79ba25ef-26d1-466f-80a6-ac6b194f6377': 65713, '7a0aa985-653e-43f5-ac36-b8f38ed1b0d0': 65876, '7b00a781-de7e-4b65-b5fa-d7ebe7b78284': 66370, '7c2d6c36-8ca8-49c0-a84c-375965d80468': 66996, '7c97da87-41ad-4a91-93ad-6429a3ebb320': 67218, '7cb3aae3-83e3-4f74-98f5-0ae4b1f50869': 67277, '7ccb9098-a36f-459a-ba13-3570ef19cd55': 67326, '7cf45ecb-5830-4e6c-9bc6-b79e7bc558b0': 67403, '7d213622-910e-4360-b060-83d3a238f3cf': 67499, '7dde34ed-6f39-4103-bb78-e7852e93f4e2': 67926, '7e54df40-9738-4b95-a4af-8c043560b8e5': 68176, '7ef607af-58fd-41eb-b420-d17a4f23e2b5': 68527, '7f73ea58-3e83-482d-a611-5bb9f5960d6e': 68813, '7fe1fd67-64a1-4462-ad7f-db90c334f0c7': 69061, '813845e1-0100-4d8c-b57b-886601bd354a': 69801, '8149821b-9edc-4867-9d2c-102dd6db0b66': 69838, '815e6927-f46f-4412-a32a-35f2575e81b6': 69878, '81785739-8550-40ad-8556-d4ed4962cf85': 69934, '8277de3e-ed6c-4475-84c2-c44dd1ea6398': 70458, '8578b49e-0174-4c28-94d4-7eabfd157030': 72028, '868a8fc4-f2b2-4f44-8122-1f9d01b49a0e': 72646, '87e263d5-99e7-45c6-931a-327fb96211ad': 73330, '87ebaaa3-8576-4f25-99f6-a545f5ffa17c': 73350, '898050ad-5694-42dc-8032-789942f3be55': 74186, '89a2a2d4-ca2a-48a4-a6bc-9db3d96b0d00': 74271, '89cbe4e5-454c-4686-a444-58ed49ddbc05': 74349, '8ba8d038-d2e8-4efc-9571-fdc5c50c60a1': 75405, '8cdb0520-75e1-44b2-a29f-1bbf21fed36f': 76056, '8cfb4d85-5c8a-4993-aa90-5d8595610451': 76126, '8e3829d4-06e3-4314-9b3a-8791eb68b35e': 76796, '8f0c49ef-58e1-4336-aca8-6356a4f6bca8': 77237, '90cb3e59-8d56-41ba-92a4-2cf208b2b91b': 78186, '927d7346-7a59-4763-b74a-d65e5d97896e': 79054, '946bf0d2-43b2-47c1-8aec-3745ba4e2fe3': 80072, '9484285d-0617-48a6-8298-477c9830859d': 80127, '9539ecc3-2bd1-4816-a363-d01b919c3619': 80518, '954f61e1-e196-4208-a094-e27fbc2b9bfd': 80564, '9738c082-b504-489e-b656-878de290457a': 81624, '97c4b89e-9fae-4e35-b91d-fb17011c412d': 81924, '98a9d191-cfb1-4f6c-aa54-42aaa837a137': 82426, '995bbbaf-7e59-4afa-acda-54ffb2738bdc': 82811, '997ec0cc-8594-44a9-8ace-b5cdb0455834': 82891, '99fdf914-94d7-4906-9cc0-5f9e3464a269': 83201, '9a6a484a-908b-4122-b98d-13a9b9e6aeea': 83433, '9b36e002-4f1a-42e3-b7fe-cefb80a46266': 83908, '9c37f070-4500-4d3e-9da0-14736acaf23c': 84436, '9c44622e-3af7-41bf-b51b-9bcd43501716': 84459, '9c5e573f-1ec3-41ba-985c-f9f372da8dc3': 84506, '9d248910-9538-43f9-8866-729751750301': 84919, '9f418d8a-53d8-4f6b-ba67-4903233f547a': 86068, 'a0162e84-62cb-48c4-aae1-78efb0ad85be': 86550, 'a0403db5-4477-4fd9-9e35-3b6cc8c78cf9': 86636, 'a040f3ee-9367-419e-aa78-767046643d45': 86642, 'a120b3d6-ba22-4099-8eca-e50ee6ee55fe': 87115, 'a13648a4-3c8f-45d4-96ae-b92eab7e4a8f': 87170, 'a1cdfadb-1c46-471a-9359-92ff3879a4d7': 87501, 'a4681aa9-8f7c-4bef-a0b6-ebbc6f2d8d7c': 88881, 'a7946afa-7193-47e6-88df-9e7270c41937': 90572, 'a8555674-4ebe-43ee-9868-903488121a5b': 90977, 'a8716882-145d-4493-b69a-bcbe88944555': 91026, 'aa492537-afcf-405a-86e0-3d9fd6ab0af3': 92045, 'add8dcb4-8a55-4ccb-bcf6-e86d67328e71': 93946, 'af9ac3e4-dd2d-4f61-8602-c11b3177a15a': 94905, 'b0169808-adc7-4d5e-a600-0e9c3206f02c': 95152, 'b01da56a-9480-4f39-8979-7e7aaeb8a4da': 95171, 'b02b935c-ef5d-4f0f-98f4-2cab9dfc8f7f': 95195, 'b0585566-c6e5-4b3e-9a2b-bdd101e18540': 95291, 'b0ed6eaf-f1b6-4896-b484-c844f4f77b51': 95579, 'b0f1e90d-e226-4076-b9d7-c0ea81afe65c': 95587, 'b2297721-9169-4b5b-aaa0-637ae92d21fa': 96242, 'b360233d-b238-4dc3-805c-7721937310ef': 96903, 'b49fb1e1-c5ac-4f7f-a472-b1f86e607bd7': 97566, 'b57d7f29-2d17-4f9e-b65a-a57a13a7df0c': 98045, 'b588ad4e-8bdf-4e88-9f2e-380fce734c2a': 98072, 'b759f294-3488-4ebc-bcf9-b3b5f3b0d685': 99073, 'b7d6d81b-e0a2-4cff-a12c-ba1b3c9d1969': 99337, 'b7f57d36-d7a5-4930-92ad-03ed2a885d65': 99394, 'b8145301-8a86-4042-9441-2d92b48b245e': 99465, 'b8d14deb-d013-4355-8656-9d9c6af2191b': 99842, 'b8dbf8e6-89b4-45d4-9f1f-78ac8396ae27': 99870, 'b96b32f1-b9f1-4a22-9acf-2a37cf3142b4': 100168, 'ba316218-fddb-4020-b1b8-b5ad7b1eaa9d': 100576, 'baacd2ca-a6f5-4fe4-9819-567bb12758f1': 100836, 'bab6228a-f2b6-43d3-bb7e-9109fc97add2': 100849, 'babcf571-be16-45c2-9c85-800eccf76ee8': 100863, 'bba73ffe-77bb-4ea5-9c6b-b4ac81222d79': 101332, 'bbd05947-dbc1-457f-b65a-96b0c5866b95': 101420, 'bcca9c3a-9820-434c-9d1e-560ce9d8e1b5': 101979, 'becb5864-1911-4bd4-831c-eb135973a0a2': 103082, 'c0241861-d449-425c-ab68-11d2e59a7455': 103868, 'c0c2566f-a8a4-4ac0-9dd2-1817f3115d00': 104222, 'c13b32a5-295f-4bdb-a480-bc16c6e880e7': 104485, 'c1ed646a-d8cb-49bd-992d-922929635d13': 104848, 'c2bac40e-368a-4760-8e25-142dc0260e07': 105278, 'c59622ce-cf1c-46bb-9839-1389172ef02c': 106826, 'c5aa2acd-c71d-4457-a1b9-909c39204ffe': 106870, 'c5c83260-1ee8-4f22-be31-f7c7de98af9f': 106963, 'c5f35ef2-0d7f-4653-b19c-7e1f1d04e212': 107046, 'c686a9ed-11f4-485d-a9bc-bdbc3ea2806d': 107368, 'c6ad180d-7801-4037-90a4-ec35426b98d0': 107458, 'c753d5ba-af00-489f-9f15-a992e5808d54': 107809, 'c76f5e4d-9046-45f6-bd08-3715809dde99': 107878, 'c7b6baad-6d17-4ab7-bf77-bdfa9d2e3f0d': 108032, 'c86037ef-97c0-415e-b0af-8a5872bc100b': 108381, 'c86c02e3-7ac5-40be-91a6-cbbce0e0f856': 108406, 'c8a3d043-8444-4643-bfee-97c848724541': 108535, 'c8e2d033-4c39-4d65-9efd-c7110f9afca9': 108659, 'c8fd412a-9e32-49b2-9d60-a0f5c2929034': 108709, 'cb6566f8-e032-452b-adce-741729cfbfe5': 109999, 'cbf99af0-7bdf-4256-aefd-cac3e52c3620': 110318, 'cc775bff-4963-4f98-a817-84f7c324d28e': 110616, 'cd80c5a1-4bf0-4ab8-9867-e62f93b9f819': 111198, 'cdb93ad9-a593-4ff6-a183-f6e4fefaed19': 111345, 'cdd65b4c-d2b8-446e-998d-9b596c0342cc': 111409, 'ce72d1a0-7baa-4b89-9060-acbc022791fb': 111721, 'd01d242a-65ad-4901-b67e-7a3a5a7df561': 112604, 'd0cd3d92-c69b-4249-8978-388bb8edb867': 113015, 'd1d37381-b2ad-4ea1-a5f9-4514d17dbc23': 113535, 'd1de0d42-f87b-4380-ad36-41bf56baf59c': 113559, 'd434c246-e624-4f7a-8fff-0b49c26bef16': 114854, 'd437b657-388c-4fcf-8034-f1db801d134f': 114860, 'd4528dc8-a605-4f73-87de-21469cba1616': 114912, 'd55b90f6-8fa8-427a-81f4-0eb54f3267e0': 115486, 'd6019f76-49ca-4ba2-ae7f-8bc5dfee6454': 115835, 'd62736b9-7362-4268-a806-f557c9669306': 115914, 'd7a6aaf7-6a55-451a-855f-4b376612635c': 116702, 'd81c0da6-aeb3-4a52-ac18-2d26c523f382': 116955, 'db1405a7-c654-4c51-aec4-128ca6c1987b': 118530, 'db990cda-fba3-4103-ba96-9b252c3dca4d': 118811, 'dbed25dd-44cb-4838-9220-2355546583d7': 119008, 'dc284cf8-c981-441b-adcb-03ab681c970b': 119122, 'dc5634c8-c4cc-4fd6-be61-f164621f7b25': 119230, 'ddd60100-356b-4abb-995d-14641fd31c98': 120018, 'e014f8ad-4a3c-477d-8068-f6f1d97cce3e': 121225, 'e1dd183a-094e-4e10-8363-b6f11e3ff329': 122231, 'e3219974-cf9e-4652-b13d-6c3283de32f8': 122976, 'e39e129a-ca5b-4c6d-b462-e0982dde7b87': 123257, 'e3dc948d-0b14-4a0c-b0e3-3e416bce803a': 123375, 'e4444815-1609-4cf9-b1f7-09e062094466': 123574, 'e460acd0-775f-440b-859f-a165b1819a80': 123641, 'e4cb621a-b0c0-4206-ac33-da8118ca47d6': 123872, 'e5049c17-7b52-484d-a4ec-ef88c9006fa8': 124001, 'e8cc1b73-b23b-4853-9a78-174eb4c6d9bf': 126100, 'e9a6db88-af51-40e9-a680-041f46dd7f11': 126538, 'e9e072a7-36d1-4d36-b59f-096144efecb5': 126686, 'e9f3a8af-1524-44b2-997f-f9ae1dc78dce': 126728, 'ea2321ea-2ba1-4d4b-a60c-93f462bdfd47': 126818, 'ea751b51-4fe8-4870-bd58-b2b8c5a3a45b': 126984, 'ea84e8d6-4941-4685-aa1f-514a72d3cf6d': 127028, 'eb8369f7-c05f-422d-a2c6-91ce197931be': 127546, 'ed935efd-a050-47ec-bc90-038167755e2e': 128619, 'eda0e780-0513-4791-9899-41ec5c24add0': 128652, 'ee6f4054-14c8-457a-9fc0-21c1a2fc9f56': 129063, 'efaec9f5-7645-438a-aaa5-7324a7a4c45b': 129772, 'efe9cbee-17aa-4887-8ced-1d40de46f244': 129914, 'f09afe90-5a22-4a14-9a6a-27093105d93b': 130288, 'f2fedded-b0b0-4570-86b1-54e38c27e846': 131543, 'f34ebbb7-9ed4-49f4-ab58-a1d31cfa8a9f': 131732, 'f36d1108-c497-4cfa-afff-0b8cd86dd82a': 131795, 'f3f26d8f-9135-4a3a-813e-3a53f0997664': 132114, 'f49f7593-538f-4f2b-8ee3-77b78db3ef4f': 132481, 'f4f299d8-5437-4f4d-bef6-0e387ba340f4': 132654, 'f70918d6-32e3-49ce-90f5-9f47f53a67c9': 133761, 'f7a197c2-245d-4661-912c-d28265b3c9a0': 134096, 'f80cfaa8-ac62-4dc7-8b6a-b32f216848a8': 134326, 'f98ba78f-ddb3-4291-a9f5-6f1999248606': 135144, 'f9a9461b-6ac0-4447-91a4-edbc4392b55b': 135211, 'fb36e8f3-6c12-4c13-9f2a-63df0ad41c4f': 136085, 'fb374683-fa54-433c-a08c-21d8ff7c7134': 136086, 'fb79f735-a679-4df2-8527-5d573d48b1f5': 136240, 'fb891781-2d22-49f5-ad4b-bbe4cfccf6d3': 136274, 'fc0e3ce5-18df-445f-900f-5b275a63e2a8': 136566, 'fd4b53ac-9ccd-4279-acc9-d392903b71ea': 137228, 'fe0baa12-cea1-4084-9ba8-894340173a2a': 137622, 'ff9b7b4d-3ae4-4280-84de-6f65f9db8a1c': 138516, 'ffc4e152-104d-4f74-8739-1f5cc85fe690': 138606}, diff: 339

In [8]:
emb_idx_df = pd.DataFrame.from_dict(metadata_dict, orient='index')
emb_idx_df.dropna(inplace=True)
emb_idx_df['TensorIdx'] = emb_idx_df['TensorIdx'].astype(int)
emb_idx_df = emb_idx_df.reset_index().rename(columns={'index': 'TrackID'})

emb_idx_df.head()

,TrackID,AlbumID,AlbumName,Artists,TensorIdx
0,1c2377e8-d3f1-4a8f-82c9-1fbede9de0d0,00016005-985e-4f11-b06d-e2f37fd65608,Taste me up!,[{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae'...,15228
1,5c27d4ff-cf85-42fc-aa51-c9856be198b3,00016005-985e-4f11-b06d-e2f37fd65608,Taste me up!,[{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae'...,49801
2,7ecfe8f0-9737-4fd5-9eaf-96770bd4226f,00016005-985e-4f11-b06d-e2f37fd65608,Taste me up!,[{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae'...,68445
3,bd12b3ff-0b53-44da-b615-118ce11b6c22,00016005-985e-4f11-b06d-e2f37fd65608,Taste me up!,[{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae'...,102141
4,c54e88c1-076e-4cc7-bce9-d861ada89ed2,00016005-985e-4f11-b06d-e2f37fd65608,Taste me up!,[{'id': 'e95a42e9-10c8-4b24-b88f-72d4626ac4ae'...,106697

In [9]:
emb_idx_df['ArtistIDList'] = emb_idx_df['Artists'].apply(lambda x: [artist['id'] for artist in x])

track_to_artists_map = pd.Series(emb_idx_df.ArtistIDList.values, index=emb_idx_df.TrackID).to_dict()
track_to_artists_map

{'1c2377e8-d3f1-4a8f-82c9-1fbede9de0d0': ['e95a42e9-10c8-4b24-b88f-72d4626ac4ae'],
 '5c27d4ff-cf85-42fc-aa51-c9856be198b3': ['e95a42e9-10c8-4b24-b88f-72d4626ac4ae'],
 '7ecfe8f0-9737-4fd5-9eaf-96770bd4226f': ['e95a42e9-10c8-4b24-b88f-72d4626ac4ae'],
 'bd12b3ff-0b53-44da-b615-118ce11b6c22': ['e95a42e9-10c8-4b24-b88f-72d4626ac4ae'],
 'c54e88c1-076e-4cc7-bce9-d861ada89ed2': ['e95a42e9-10c8-4b24-b88f-72d4626ac4ae'],
 'cf588af1-8ad4-4ea4-9ca7-466a14643d92': ['e95a42e9-10c8-4b24-b88f-72d4626ac4ae'],
 'cf72b9a9-292f-451b-8f03-c3e54304b6ea': ['e95a42e9-10c8-4b24-b88f-72d4626ac4ae'],
 'd173f51d-fa33-4c09-aeed-91c468d5b208': ['e95a42e9-10c8-4b24-b88f-72d4626ac4ae'],
 'd33ff253-f4f0-4f2e-80c6-c6f06fbb6ca1': ['e95a42e9-10c8-4b24-b88f-72d4626ac4ae'],
 'f4808ffc-979c-42ea-90a4-462e82fb47eb': ['e95a42e9-10c8-4b24-b88f-72d4626ac4ae'],
 'fadcd744-aba8-47e1-8c2c-6e3da7e6c5f9': ['e95a42e9-10c8-4b24-b88f-72d4626ac4ae'],
 '558d16f1-dea1-461e-a000-3edd2308d377': ['6cd927f5-808e-48b9-85db-1625a0e35114'],
 '5b9ca6a8-4592-4449-8273-3ae8bf98181c': ['6cd927f5-808e-48b9-85db-1625a0e35114'],
 '62b266e7-0528-4569-b5cd-d3a882cd9c45': ['6cd927f5-808e-48b9-85db-1625a0e35114'],
 '67f45f93-07ee-420d-8310-eac15917d5e5': ['6cd927f5-808e-48b9-85db-1625a0e35114'],
 '85ac420a-f353-46ca-8f90-32fa5d3a7608': ['6cd927f5-808e-48b9-85db-1625a0e35114'],
 'c5b6438f-a2ac-48db-8d72-712521546820': ['6cd927f5-808e-48b9-85db-1625a0e35114'],
 'e977e41a-9b80-463a-99ba-36c65d3e08be': ['6cd927f5-808e-48b9-85db-1625a0e35114'],
 'f37b05a5-b1b5-480d-996b-a30792bdf17c': ['6cd927f5-808e-48b9-85db-1625a0e35114'],
 'fedb5022-576f-4cf3-a82d-4274ff6fffed': ['6cd927f5-808e-48b9-85db-1625a0e35114'],
 '4abda64d-26f9-41c7-bc3c-e04451ce0828': ['7725a3ee-3a92-4eb6-b5cd-b5461d402e89'],
 '4b1d1d4e-1e17-411f-a227-4c5857267875': ['7725a3ee-3a92-4eb6-b5cd-b5461d402e89'],
 '574bab53-8b10-4585-80e0-11cb447b3090': ['7725a3ee-3a92-4eb6-b5cd-b5461d402e89'],
 '87bdccb7-499f-4657-afaf-3cd1709dface': ['7725a3ee-3a92-4eb6-b5cd-b5461d402e89'],
 '8b2174e7-e14b-4737-a5ae-e25dc3f116a1': ['7725a3ee-3a92-4eb6-b5cd-b5461d402e89'],
 '95f3b295-fd58-4ee9-92b2-3a244071988c': ['7725a3ee-3a92-4eb6-b5cd-b5461d402e89'],
 'a63a23b7-863a-49e4-a7f4-5be3326aaae3': ['7725a3ee-3a92-4eb6-b5cd-b5461d402e89'],
 'af068d08-5e2d-4ded-9e3c-d6c53bd2225e': ['7725a3ee-3a92-4eb6-b5cd-b5461d402e89'],
 'cef084e0-6de2-4a9f-a44a-c48d97b72f15': ['7725a3ee-3a92-4eb6-b5cd-b5461d402e89'],
 'f290719c-3df8-4982-a232-70f3522eb512': ['7725a3ee-3a92-4eb6-b5cd-b5461d402e89'],
 '1394406d-1174-40af-bf53-459d637db3d6': ['faa689b4-b345-4e0d-be19-066eebf55a56'],
 '1aa164fd-0c2b-409f-b2a7-55ed6482b55b': ['faa689b4-b345-4e0d-be19-066eebf55a56'],
 '3b283138-bad8-4438-bb2c-19266728bc16': ['faa689b4-b345-4e0d-be19-066eebf55a56'],
 '5b0d9b6b-8f3f-4d07-99c3-fefff9feb91d': ['faa689b4-b345-4e0d-be19-066eebf55a56'],
 'b7ef83b7-aa7e-4aa8-8201-9fab3cb8a2e8': ['faa689b4-b345-4e0d-be19-066eebf55a56'],
 '20ddf75c-7bfe-43af-aeab-d1dca2e45364': ['a6065265-6413-4541-bc7e-e7f466666dd0'],
 '32759cb1-e549-4fc0-9426-d681232d613f': ['a6065265-6413-4541-bc7e-e7f466666dd0'],
 '8daadb15-41b2-4e13-a311-67fdd9d1d401': ['a6065265-6413-4541-bc7e-e7f466666dd0'],
 '9fc822d3-407f-4ebd-a88c-741855a34586': ['a6065265-6413-4541-bc7e-e7f466666dd0'],
 'b70544a3-a6d5-4a82-8a93-e734371d9d7a': ['a6065265-6413-4541-bc7e-e7f466666dd0'],
 'be0d1b87-1977-4c50-9523-1bff931adc2e': ['a6065265-6413-4541-bc7e-e7f466666dd0'],
 'd3e1d7e9-1e86-4c62-baeb-deb8044e2229': ['a6065265-6413-4541-bc7e-e7f466666dd0'],
 'd59246f4-4a81-4060-ada6-43a32e7e5d9b': ['a6065265-6413-4541-bc7e-e7f466666dd0'],
 'd8d9d9d7-3faa-476e-9b2c-089e85d930c6': ['a6065265-6413-4541-bc7e-e7f466666dd0'],
 'f52d23c4-ec6f-42a0-a186-46e69b7ceb93': ['a6065265-6413-4541-bc7e-e7f466666dd0'],
 '0d95a570-8de5-416c-bde4-a9db29e5bc7e': ['2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a'],
 '1d4c0580-8029-47b8-acec-00bcf1bfac18': ['2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a'],
 '26ae3845-9b39-433e-85b8-9a31f4b9c963': ['2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a'],
 '2b4edfd8-7b91-4a78-8bad-e178857c3865': ['2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a'],
 '37b9cdba-d24d-4056-a081-c7374ef5841f': ['2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a'],
 '58426d79-b837-4519-9f7a-de68e4843459': ['2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a'],
 '635d2598-cb1f-4abf-b196-e461fd7ca5c6': ['2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a'],
 '67d2cfd4-af71-470a-a7d4-6298111ead52': ['2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a'],
 '70825a0c-4d55-4790-b3f6-befea9c3714e': ['2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a'],
 '805604dd-2823-4f2f-b811-bbafcfd5884b': ['2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a'],
 'fb69c0c0-e9c6-4744-8ad0-7b75b3f071c2': ['2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a'],
 '0b45a6e6-6bfa-4459-befe-7c7031ee8770': ['5889af12-024d-4aa8-8471-c3897643c1a1'],
 '4aef4c76-e32c-4449-9994-bd2326d2a0e0': ['5889af12-024d-4aa8-8471-c3897643c1a1'],
 '525dbb74-37c4-4444-b503-6e80f965638a': ['5889af12-024d-4aa8-8471-c3897643c1a1'],
 '611d07d9-8cce-4bc2-8824-a315b6409251': ['5889af12-024d-4aa8-8471-c3897643c1a1'],
 '79604a51-1f5a-4fe4-94f1-e7023cd6f100': ['5889af12-024d-4aa8-8471-c3897643c1a1'],
 '7fd7ab19-aacc-43f6-9951-39a0c8b7f66f': ['5889af12-024d-4aa8-8471-c3897643c1a1'],
 '8abbe28e-3a98-4907-ab13-2f7eb91f90c7': ['5889af12-024d-4aa8-8471-c3897643c1a1'],
 '922eda50-151e-4e16-a7ac-005561744803': ['5889af12-024d-4aa8-8471-c3897643c1a1'],
 'a45d93d1-4cf1-44ed-aaed-f0ff851cb437': ['5889af12-024d-4aa8-8471-c3897643c1a1'],
 '0565a847-99a8-40ff-9ad3-ce136f1c7ec2': ['fd7ab46d-4205-4e15-a9d9-64a2a1d9696b'],
 '25442fec-c343-4c7e-a895-f141736c1569': ['fd7ab46d-4205-4e15-a9d9-64a2a1d9696b'],
 '2d2df3ad-63c3-4d46-9985-dcda413710e7': ['fd7ab46d-4205-4e15-a9d9-64a2a1d9696b'],
 'ae437248-3963-45c3-abbb-c5370541a13b': ['fd7ab46d-4205-4e15-a9d9-64a2a1d9696b'],
 'f3057dad-8acb-4672-a860-0988d900f937': ['fd7ab46d-4205-4e15-a9d9-64a2a1d9696b'],
 '10cd10f6-46ef-4338-a14c-0cab07030bd3': ['ca0e5dcc-3257-4043-8478-fe89a964ae45'],
 '38cbea63-91ab-4a80-acb6-aea34e6fcebe': ['ca0e5dcc-3257-4043-8478-fe89a964ae45'],
 'ae2b145c-df49-44d9-b233-0e2ccb2e58f0': ['ca0e5dcc-3257-4043-8478-fe89a964ae45'],
 'bb97bc6e-001d-41ac-b5ad-6fbeb9bd19d0': ['ca0e5dcc-3257-4043-8478-fe89a964ae45'],
 'f4627501-e16d-4701-9ef6-4e0571f4dc93': ['ca0e5dcc-3257-4043-8478-fe89a964ae45'],
 '5d7d5cf2-d200-42ad-a126-c812e97767ee': ['274858c2-7e1b-4b5f-8d0b-6e2dc378c787'],
 '7a2f4f08-b8c6-457b-8dda-6358c4513f0d': ['274858c2-7e1b-4b5f-8d0b-6e2dc378c787'],
 '9b0e7310-0677-4770-a0f9-c0abd9deb6b1': ['274858c2-7e1b-4b5f-8d0b-6e2dc378c787'],
 'bc2266a1-6e8c-49fc-888a-96ee81633b1b': ['274858c2-7e1b-4b5f-8d0b-6e2dc378c787'],
 'c0dc92b9-709e-4d0e-b7da-04896655da34': ['274858c2-7e1b-4b5f-8d0b-6e2dc378c787'],
 'd3d8dd57-17dd-4291-af0a-df4b5144eb33': ['274858c2-7e1b-4b5f-8d0b-6e2dc378c787'],
 '11969b07-ad7d-43e3-9113-00a40f392981': ['e0c4510a-90ec-4932-a3c4-3bb511a00aa3'],
 '30e83ad8-dc67-4d5d-a8ae-efe6d351f82f': ['e0c4510a-90ec-4932-a3c4-3bb511a00aa3'],
 '3f0f4c35-716a-4d7a-8e22-857518bf980a': ['e0c4510a-90ec-4932-a3c4-3bb511a00aa3'],
 '4b4b0859-4a0d-4a30-ab8a-e6db1d198e5d': ['e0c4510a-90ec-4932-a3c4-3bb511a00aa3'],
 '59333c87-867d-4b56-9957-73eb32e0543a': ['e0c4510a-90ec-4932-a3c4-3bb511a00aa3'],
 '8a8eb85d-567f-4b5e-bba4-163157f07468': ['e0c4510a-90ec-4932-a3c4-3bb511a00aa3'],
 'b602c864-74ce-4595-9653-8184d586a4a1': ['e0c4510a-90ec-4932-a3c4-3bb511a00aa3'],
 'd7a0e100-0a2a-4758-b098-81615b04b7ad': ['e0c4510a-90ec-4932-a3c4-3bb511a00aa3'],
 '012822ee-b7b1-477c-abe4-dddda0c3e6f0': ['dc84e236-015d-495f-a8b2-1e2e8db3fd5d'],
 '16d778d2-bc2a-4efa-b019-29615607bbff': ['dc84e236-015d-495f-a8b2-1e2e8db3fd5d'],
 '28f8a716-0844-435f-a2cf-90c13f6fa143': ['dc84e236-015d-495f-a8b2-1e2e8db3fd5d'],
 '2b1bc473-9d16-4d9e-a996-e1ee2a5f2960': ['dc84e236-015d-495f-a8b2-1e2e8db3fd5d'],
 '3082699c-caab-4fae-8bc7-c83e4679e0a5': ['dc84e236-015d-495f-a8b2-1e2e8db3fd5d'],
 '49795388-19e3-480f-80ab-6626af64741b': ['dc84e236-015d-495f-a8b2-1e2e8db3fd5d'],
 '58ce152a-81b0-4091-b54c-b8d21d2cd3ab': ['dc84e236-015d-495f-a8b2-1e2e8db3fd5d'],
 '76830b1f-5618-4357-93f1-7568729e162c': ['dc84e236-015d-495f-a8b2-1e2e8db3fd5d'],
 'beccf035-183e-437d-a6ce-6071d11cc308': ['dc84e236-015d-495f-a8b2-1e2e8db3fd5d'],
 'c46268a5-747c-40b9-bbd2-e3ecd66ed25a': ['dc84e236-015d-495f-a8b2-1e2e8db3fd5d'],
 'd2681a38-68fb-40c5-8856-9c30c064e16c': ['dc84e236-015d-495f-a8b2-1e2e8db3fd5d'],
 'ddf72e00-e766-4d6c-bee9-99c6cb51917f': ['dc84e236-015d-495f-a8b2-1e2e8db3fd5d'],
 'e8481952-448d-4a98-ac20-c2e3d5e7f34f': ['dc84e236-015d-495f-a8b2-1e2e8db3fd5d'],
 'fb397bf8-5408-49a9-9501-71d28a79a006': ['dc84e236-015d-495f-a8b2-1e2e8db3fd5d'],
 '13ecc8d4-a176-47db-b173-807c9a126c9c': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 '27eb2b3c-1a37-4fb5-a9a1-813d09a3bdc8': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 '2a379cfd-bf65-4795-a78b-505495d3a7d1': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 '328e7616-e35e-43ab-8724-1b7c1217ebaa': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 '515031db-5776-4c0a-b80b-01e74fd7d897': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 '613ba9a1-9109-4174-9307-0c2b0272c596': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 '6c442436-46cc-4024-809a-fe66705db859': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 '8044a76f-bc93-42b8-9c0c-30f49e5f83e9': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 '95929716-7611-4f0b-8279-b344cfe0324c': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 '98053266-872f-468b-b8fa-cdcb9a38376e': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 '9a392445-b99b-41ed-95f2-f81b0dac5e66': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 'b7f913c8-3c4c-475e-8bd6-063431cacdac': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 'bfe7e6ea-328e-4e66-9a53-1bc5236f816d': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 'c62b9bdb-9ba0-4fd0-8da0-765691b36478': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 'e0f217aa-cbd5-4ecf-a3b3-c55d7be497ca': ['4e0b42f6-d779-40ad-842b-c249f9a4675f'],
 '0723f644-8f1d-44c0-a48e-46699738eef4': ['cdb9f02b-c28b-44e3-ae27-322610fd623d'],
 '07780d34-40b6-442e-9950-9830fedc47cd': ['cdb9f02b-c28b-44e3-ae27-322610fd623d'],
 '7f762c49-ba37-4ffe-b565-42c5bd261bf1': ['cdb9f02b-c28b-44e3-ae27-322610fd623d'],
 '8695aa5f-1366-4e52-a034-e8292fc9d31d': ['cdb9f02b-c28b-44e3-ae27-322610fd623d'],
 '8ae40e04-9b1e-496a-90a5-f56b3a1cfb86': ['cdb9f02b-c28b-44e3-ae27-322610fd623d'],
 'c30859a0-8f5f-4b6d-bd2a-beece1f116ab': ['cdb9f02b-c28b-44e3-ae27-322610fd623d'],
 'd6d2878a-96b5-4ce9-b290-65de41f5ebe7': ['cdb9f02b-c28b-44e3-ae27-322610fd623d'],
 'fa061ac1-ba17-47ac-bba4-195b53baed24': ['cdb9f02b-c28b-44e3-ae27-322610fd623d'],
 '6c742deb-c0fe-46da-a5dd-6928c82c65c4': ['45aa2b1e-57ec-4841-8781-1ade06a6a187'],
 '032539bd-9357-41b7-9d28-f28e02f455b9': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 '2ac16cb6-c752-404a-b32a-ab0e66c4a716': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 '459d17f6-b490-4cdb-ae40-e5fd6ac9b26c': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 '45e36599-6586-4660-9b7d-4e3369c83b14': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 '516c051a-7c75-4740-b678-112bf58279a4': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 '523eebe6-644c-44f3-968e-2b20b8858df0': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 '95987e9d-9c30-4f5f-97dc-5b3d4192c1d8': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 'b5120ff2-3bd9-47e1-a536-f53aca5f8c9b': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 'c3f8cb1b-a0bf-4556-b5e7-a21ff86f9b75': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 'c5594bd7-c336-4476-8b2a-a2d011ce2f83': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 '218d228a-a8c0-46cf-906e-9b93ce51322f': ['2a9928f4-b0e2-4d7b-8720-c74f8e422edb'],
 '23b90802-c2eb-4b18-9af5-0e197ffbede0': ['2a9928f4-b0e2-4d7b-8720-c74f8e422edb'],
 '2b56965c-453f-4b4e-ae2d-0013096a77df': ['2a9928f4-b0e2-4d7b-8720-c74f8e422edb'],
 '3103b95c-7366-4e0a-b744-79369ef5ec66': ['2a9928f4-b0e2-4d7b-8720-c74f8e422edb'],
 '363a21b4-1aeb-44a6-8b4a-63925504c4f0': ['2a9928f4-b0e2-4d7b-8720-c74f8e422edb'],
 '700391fd-7fd7-43a2-b529-32c9ee937eaf': ['2a9928f4-b0e2-4d7b-8720-c74f8e422edb'],
 '7c89a9b4-57da-4188-b4cf-0b098772052f': ['2a9928f4-b0e2-4d7b-8720-c74f8e422edb'],
 'a107c1e2-1d7c-4626-9fde-dda110cf3ec5': ['2a9928f4-b0e2-4d7b-8720-c74f8e422edb'],
 'aa42c326-358f-4cc4-8a0a-6ac506dcb0a9': ['2a9928f4-b0e2-4d7b-8720-c74f8e422edb'],
 'fe66717f-f54e-4d76-bb23-b31c2d771a10': ['2a9928f4-b0e2-4d7b-8720-c74f8e422edb'],
 '12937629-c40b-4a71-a655-e88ca865b726': ['59c5ad70-a285-41ee-95dd-fe87a45b65a9'],
 '28f5b2f4-0731-43b2-99ed-a1869ae96e87': ['59c5ad70-a285-41ee-95dd-fe87a45b65a9'],
 '62fa20d4-6634-41a4-a151-c3894ce081f2': ['59c5ad70-a285-41ee-95dd-fe87a45b65a9'],
 'b97a8b97-1fa9-4338-9e8c-5d422f26964a': ['59c5ad70-a285-41ee-95dd-fe87a45b65a9'],
 'c9f1f9d7-3584-40fb-b0b7-43ddb1ef4cfe': ['59c5ad70-a285-41ee-95dd-fe87a45b65a9'],
 'd35c7c49-73dc-422d-8ad9-d9ffbd9fed5a': ['59c5ad70-a285-41ee-95dd-fe87a45b65a9'],
 '057746e0-b1ee-41e8-8277-8787f36bddb2': ['559432e5-d103-4b32-b099-e075f4946aeb'],
 '11ba37cd-55a4-4358-8faf-c126ce81b05f': ['559432e5-d103-4b32-b099-e075f4946aeb'],
 '6fe735c0-2c02-445e-84db-08fd302198ea': ['559432e5-d103-4b32-b099-e075f4946aeb'],
 '81487ba0-8239-47cf-96f0-a0df924862c9': ['559432e5-d103-4b32-b099-e075f4946aeb'],
 '9501a2f6-edf8-4549-ba81-b522a5a71b4a': ['559432e5-d103-4b32-b099-e075f4946aeb'],
 'b6dd01a3-c637-4324-bba2-d5654dd1fcba': ['559432e5-d103-4b32-b099-e075f4946aeb'],
 'd05f809b-fa82-4d6f-b65b-56e58bd9bee0': ['559432e5-d103-4b32-b099-e075f4946aeb'],
 '3429b6d3-49a4-4247-ba0c-af74668a0d8c': ['829dd0b1-8aaa-4f92-bc79-ea9f3ec72479'],
 '3d693f45-0c98-47e1-914a-a9048becab12': ['829dd0b1-8aaa-4f92-bc79-ea9f3ec72479'],
 '6722228a-8686-4764-8b3c-8cf599ffd17e': ['829dd0b1-8aaa-4f92-bc79-ea9f3ec72479'],
 '70a4aa3c-3546-47c2-a1ff-07380f46b5dc': ['829dd0b1-8aaa-4f92-bc79-ea9f3ec72479'],
 '77bd1443-afa4-413c-8670-1647aa830cb5': ['829dd0b1-8aaa-4f92-bc79-ea9f3ec72479'],
 '89fd0cb5-ae49-4fa6-970a-3814802e9a80': ['829dd0b1-8aaa-4f92-bc79-ea9f3ec72479'],
 '8ae410b1-4e6b-4a8e-9dee-84a1d95ec8df': ['829dd0b1-8aaa-4f92-bc79-ea9f3ec72479'],
 'ad475478-af1a-4d1a-a703-70d2b26d6387': ['829dd0b1-8aaa-4f92-bc79-ea9f3ec72479'],
 'b060cd30-2946-4dcc-8adb-7f9323edf5aa': ['829dd0b1-8aaa-4f92-bc79-ea9f3ec72479'],
 'dd34c168-5c70-46c7-a206-1c13624c6764': ['829dd0b1-8aaa-4f92-bc79-ea9f3ec72479'],
 'e68442ba-b2d8-4225-9594-1616414121ae': ['829dd0b1-8aaa-4f92-bc79-ea9f3ec72479'],
 'f7893d74-9536-450e-8c12-eee023fc7e87': ['829dd0b1-8aaa-4f92-bc79-ea9f3ec72479'],
 '23ca9fb8-468f-4270-9c30-40482d0a03dc': ['6b18c9ae-94c2-485b-a240-0bb3d6ec8314'],
 '24270342-aa37-453b-b7ea-6443d0e4cdf3': ['6b18c9ae-94c2-485b-a240-0bb3d6ec8314'],
 '2bce3c90-54e2-4f2f-b241-cc7452ebe652': ['6b18c9ae-94c2-485b-a240-0bb3d6ec8314'],
 '41ab7b8b-0dd1-4b7a-a606-0c3f4570b0f1': ['6b18c9ae-94c2-485b-a240-0bb3d6ec8314'],
 '6969f99e-e908-425b-b8a5-a1f4e4d2e975': ['6b18c9ae-94c2-485b-a240-0bb3d6ec8314'],
 '73ef5104-0efe-4dfb-8bdf-abad7c4a30ab': ['6b18c9ae-94c2-485b-a240-0bb3d6ec8314'],
 '81ebc827-454f-4aba-ac60-c082ba93fed1': ['6b18c9ae-94c2-485b-a240-0bb3d6ec8314'],
 '8e114de4-6021-4760-a5ae-8e402e5d8788': ['6b18c9ae-94c2-485b-a240-0bb3d6ec8314'],
 '985e7a8c-b056-4dc6-8622-618635dfd55b': ['6b18c9ae-94c2-485b-a240-0bb3d6ec8314'],
 '99546179-60c8-4510-b285-348f946d394a': ['6b18c9ae-94c2-485b-a240-0bb3d6ec8314'],
 'a906ad7b-cf28-4a58-b7dc-990b6fa4deb9': ['6b18c9ae-94c2-485b-a240-0bb3d6ec8314'],
 '07d55c83-798c-46a7-b9c0-1e3502bcd833': ['c95b4af9-cdc6-4fa5-b5ff-0428d4701580'],
 '191526d4-cd37-4fce-ba85-5783fcb6d0d7': ['c95b4af9-cdc6-4fa5-b5ff-0428d4701580'],
 '4e62047c-a83f-4850-ae11-211f4cdf4ff0': ['c95b4af9-cdc6-4fa5-b5ff-0428d4701580'],
 '5bfead61-f071-4fe8-9e62-7105af9d9448': ['c95b4af9-cdc6-4fa5-b5ff-0428d4701580'],
 '5d74bc0a-4b2f-4939-ad82-481d5c684f10': ['c95b4af9-cdc6-4fa5-b5ff-0428d4701580'],
 '71051223-ebba-4c7b-b09c-870b2676dbe1': ['c95b4af9-cdc6-4fa5-b5ff-0428d4701580'],
 '7146eef9-c521-46e0-b34d-835c14ff8ed7': ['c95b4af9-cdc6-4fa5-b5ff-0428d4701580'],
 '9e396cb3-68dd-4ed6-b2a1-b94546c0ea77': ['c95b4af9-cdc6-4fa5-b5ff-0428d4701580'],
 'cbf712a1-7ac0-481f-ab95-f6e5bca84e1c': ['c95b4af9-cdc6-4fa5-b5ff-0428d4701580'],
 'cd56eec2-d9df-4190-ab46-a7b1cead7158': ['c95b4af9-cdc6-4fa5-b5ff-0428d4701580'],
 'cd784e7a-2b86-48ff-ad82-65e49b1f1a56': ['c95b4af9-cdc6-4fa5-b5ff-0428d4701580'],
 'eeadf5c1-70ed-4730-ab5b-497618f17b8e': ['c95b4af9-cdc6-4fa5-b5ff-0428d4701580'],
 '1569cece-4ac5-47ca-a534-c8f15bf44d41': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 '28ec4223-de82-4a6e-92de-28fc4053532a': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 '29af7391-5f12-4ebb-b9a2-e3784b1d0435': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 '3cf31db7-5288-4e46-bffe-3b45449f2c1f': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 '4c43dbb4-6d97-41ff-b7ca-d193c955aaaf': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 '4dc2f6e8-ec7f-464b-bca8-c68580f05810': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 'c02fae83-b83a-4690-bfde-02c1dd6b07d0': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 'c6374302-ca5d-4cc6-97e7-914e08f11952': ['80ab5a67-2a27-4ca9-9580-e24c9c61084e'],
 '32a60613-7957-4612-a875-79187bfad822': ['0df7f243-8a6a-4d8f-81bb-1831523ff917'],
 '3535ab5c-c2c0-41b0-ab45-abc21df874ae': ['0df7f243-8a6a-4d8f-81bb-1831523ff917'],
 '7be75a16-0381-4f70-8b01-452dc83ccbc5': ['0df7f243-8a6a-4d8f-81bb-1831523ff917'],
 '881e2e61-0878-435b-b59d-dd7ddbfb3a33': ['0df7f243-8a6a-4d8f-81bb-1831523ff917'],
 'a2ab1a5f-5980-45c1-8f2a-9b94fc6ba621': ['0df7f243-8a6a-4d8f-81bb-1831523ff917'],
 'a9938d1f-b3ee-404f-9baa-53b77b4d16c1': ['0df7f243-8a6a-4d8f-81bb-1831523ff917'],
 'bf31760a-f418-47b8-be56-3241d6dabc3e': ['0df7f243-8a6a-4d8f-81bb-1831523ff917'],
 'cc0941e0-6398-4c8a-93fd-c9d329c5556c': ['0df7f243-8a6a-4d8f-81bb-1831523ff917'],
 'd0c184dd-9495-45ed-a19d-785144a82aee': ['0df7f243-8a6a-4d8f-81bb-1831523ff917'],
 'df820383-7ff4-42c5-b64c-04cc77a8568d': ['0df7f243-8a6a-4d8f-81bb-1831523ff917'],
 '19a9d2b1-97df-42c5-8741-844c53144741': ['007789b8-3a02-46ed-bf0c-c2bc53c25c88'],
 '2c3fce57-72aa-438c-8234-d074aaac671f': ['007789b8-3a02-46ed-bf0c-c2bc53c25c88'],
 '74dbed8a-cdad-403b-9c8f-d72ee490922f': ['007789b8-3a02-46ed-bf0c-c2bc53c25c88'],
 'a32931a4-b5a3-4ca8-b427-23f0f65e4ee7': ['007789b8-3a02-46ed-bf0c-c2bc53c25c88'],
 'a4f5fac8-49d8-486d-b2eb-fda7623e7f96': ['007789b8-3a02-46ed-bf0c-c2bc53c25c88'],
 'ade512ae-3a2b-4400-9b11-f3298722a6ee': ['007789b8-3a02-46ed-bf0c-c2bc53c25c88'],
 '2a00a3eb-8111-4da9-9f31-836a2a861f60': ['c786f51f-2cdf-46c1-a2cd-19fd7ef0debd'],
 '2a05ccd3-c074-455c-a070-e10f537a7eb0': ['c786f51f-2cdf-46c1-a2cd-19fd7ef0debd'],
 '2bbea161-aa73-474a-8f1d-d4ab48fb28bb': ['c786f51f-2cdf-46c1-a2cd-19fd7ef0debd'],
 '33713536-01fd-40ee-8b5f-4e0c39cfe5ae': ['c786f51f-2cdf-46c1-a2cd-19fd7ef0debd'],
 '75bb2020-b6ec-4d67-9bbe-c95a44ceaca8': ['c786f51f-2cdf-46c1-a2cd-19fd7ef0debd'],
 'c9ad294f-c5f3-42d0-a350-c975d44007fd': ['c786f51f-2cdf-46c1-a2cd-19fd7ef0debd'],
 '22d01cd4-6e09-4053-99b4-f5d7e079790f': ['a9c23b07-548a-41c8-a98a-47ed7562f2f3'],
 '52b75bcb-ee58-4028-ad21-f856b37fae14': ['a9c23b07-548a-41c8-a98a-47ed7562f2f3'],
 'a0e72186-bd11-413c-9d49-25b7b41b01eb': ['a9c23b07-548a-41c8-a98a-47ed7562f2f3'],
 'fb06d9e2-d2c4-466f-ab2b-4f1abc8d453d': ['a9c23b07-548a-41c8-a98a-47ed7562f2f3'],
 '02bb1bdb-c497-43bf-824c-d45c8e703379': ['3d208da3-6d20-4a03-8155-9db44c046915'],
 '0f50440e-0953-4d93-8664-3d65c81b303a': ['3d208da3-6d20-4a03-8155-9db44c046915'],
 '11e1baeb-519b-4db7-bdd6-e062c461ecf9': ['3d208da3-6d20-4a03-8155-9db44c046915'],
 '167b2a6e-fc2c-41e2-b7b5-c1734aff7ff5': ['3d208da3-6d20-4a03-8155-9db44c046915'],
 '2edd8ee7-2ef9-4791-96b4-8b889ddbe757': ['3d208da3-6d20-4a03-8155-9db44c046915'],
 '473ca206-eef5-4fe4-962c-9fd3953c08dc': ['3d208da3-6d20-4a03-8155-9db44c046915'],
 '4a1e41fe-5014-411e-9acd-4358076023d9': ['3d208da3-6d20-4a03-8155-9db44c046915'],
 '61ef974d-a091-4d2c-9970-5a4f44f5b5e5': ['3d208da3-6d20-4a03-8155-9db44c046915'],
 '64b6822d-0d06-4569-a955-0563faed3e62': ['3d208da3-6d20-4a03-8155-9db44c046915'],
 '70d6b0f7-08ad-4b24-9c48-2684edff5e79': ['3d208da3-6d20-4a03-8155-9db44c046915'],
 '83d4c4a5-5483-43f3-8ca9-fbb9dfd476d0': ['3d208da3-6d20-4a03-8155-9db44c046915'],

In [ ]:
pooling_policies = ["mean", "mean+max"]
# pooled embeddings
all_embeddings = utils.pool_loaded_tensor_dict(
  tensors=tensors, mode='mean+max'
)

Detected allchunks tensors, pooling to 1D embedding (mean+max)

100%|██████████| 138748/138748 [00:02<00:00, 46297.66it/s]

In [ ]:
from typing import Dict, List
from collections import defaultdict

# compute centroid for each artist
artist_to_track_indicies: Dict[str, List[int]] = defaultdict(list)

track_id_to_idx = emb_idx_df.set_index("TrackID").to_dict(orient="index")

for track_id, metadata in track_id_to_idx.items():
  for artist in metadata['Artists']:
    artist_to_track_indicies[artist['id']].append(metadata['TensorIdx'])

embedding_mat = np.array(list(all_embeddings.values()))
artist_centroid: Dict[str, np.ndarray] = {}
for artist, track_indicies in artist_to_track_indicies.items():
  track_embeds = embedding_mat[np.array(track_indicies)]
  artist_centroid[artist] = track_embeds.mean(axis=0)

artist_centroid

{'e95a42e9-10c8-4b24-b88f-72d4626ac4ae': array([ 0.01052091,  0.01198753, -0.00153312, ...,  0.00815917,
         0.01135257,  0.01014479], dtype=float32),
 '6cd927f5-808e-48b9-85db-1625a0e35114': array([0.0082783 , 0.01477114, 0.00152859, ..., 0.00838992, 0.01047316,
        0.01220383], dtype=float32),
 '7725a3ee-3a92-4eb6-b5cd-b5461d402e89': array([ 0.01017172,  0.01261758, -0.00069952, ...,  0.00767819,
         0.0109442 ,  0.01135653], dtype=float32),
 'faa689b4-b345-4e0d-be19-066eebf55a56': array([ 0.00837497,  0.01492363, -0.00130169, ...,  0.00567051,
         0.01068038,  0.00913306], dtype=float32),
 'a6065265-6413-4541-bc7e-e7f466666dd0': array([0.00923053, 0.01318991, 0.00108577, ..., 0.0073954 , 0.01024916,
        0.0118218 ], dtype=float32),
 '2d047b2b-90d0-4b22-aa59-2f0d64c3bd6a': array([0.00857806, 0.01262907, 0.00178784, ..., 0.0073542 , 0.01143436,
        0.01172571], dtype=float32),
 '5889af12-024d-4aa8-8471-c3897643c1a1': array([0.00885605, 0.0137177 , 0.00225191, ..., 0.00936144, 0.01158888,
        0.01241271], dtype=float32),
 'fd7ab46d-4205-4e15-a9d9-64a2a1d9696b': array([0.00899292, 0.0146106 , 0.00169507, ..., 0.0064093 , 0.01131698,
        0.01073527], dtype=float32),
 'ca0e5dcc-3257-4043-8478-fe89a964ae45': array([0.00297903, 0.00587179, 0.00595794, ..., 0.00644231, 0.00454145,
        0.01077293], dtype=float32),
 '274858c2-7e1b-4b5f-8d0b-6e2dc378c787': array([ 0.00925536,  0.01563667, -0.00040777, ...,  0.00832324,
         0.01043912,  0.01235587], dtype=float32),
 'e0c4510a-90ec-4932-a3c4-3bb511a00aa3': array([0.00994045, 0.01516661, 0.00075197, ..., 0.01051916, 0.01038403,
        0.01241052], dtype=float32),
 'dc84e236-015d-495f-a8b2-1e2e8db3fd5d': array([0.00819539, 0.01419587, 0.0022387 , ..., 0.00988969, 0.00862537,
        0.01349432], dtype=float32),
 '4e0b42f6-d779-40ad-842b-c249f9a4675f': array([ 9.29564051e-03,  1.28657995e-02, -8.29993223e-05, ...,
         9.01560206e-03,  1.09431483e-02,  1.12982877e-02], dtype=float32),
 'cdb9f02b-c28b-44e3-ae27-322610fd623d': array([0.00962167, 0.0151436 , 0.00105921, ..., 0.00801811, 0.01205717,
        0.01013739], dtype=float32),
 '45aa2b1e-57ec-4841-8781-1ade06a6a187': array([0.00936548, 0.01656888, 0.00071599, ..., 0.010037  , 0.01098722,
        0.01183812], dtype=float32),
 '80ab5a67-2a27-4ca9-9580-e24c9c61084e': array([9.7556151e-03, 1.2256734e-02, 7.7153918e-06, ..., 9.7796638e-03,
        1.1278417e-02, 1.2038838e-02], dtype=float32),
 '2a9928f4-b0e2-4d7b-8720-c74f8e422edb': array([0.00902613, 0.01203175, 0.00064969, ..., 0.00887275, 0.01288287,
        0.01182973], dtype=float32),
 '59c5ad70-a285-41ee-95dd-fe87a45b65a9': array([0.00879146, 0.01249255, 0.00131555, ..., 0.00793216, 0.01304236,
        0.01189468], dtype=float32),
 '559432e5-d103-4b32-b099-e075f4946aeb': array([0.0089132 , 0.01206343, 0.00056695, ..., 0.00881932, 0.00944574,
        0.01277345], dtype=float32),
 '829dd0b1-8aaa-4f92-bc79-ea9f3ec72479': array([0.00683061, 0.00923275, 0.00029384, ..., 0.00764056, 0.00948599,
        0.01407743], dtype=float32),
 '6b18c9ae-94c2-485b-a240-0bb3d6ec8314': array([0.00983482, 0.01501332, 0.00129723, ..., 0.00849315, 0.01556738,
        0.01151649], dtype=float32),
 'c95b4af9-cdc6-4fa5-b5ff-0428d4701580': array([0.00748292, 0.01331757, 0.00185521, ..., 0.00909539, 0.00834573,
        0.01409294], dtype=float32),
 '0df7f243-8a6a-4d8f-81bb-1831523ff917': array([1.0170191e-02, 1.6260102e-02, 4.5958723e-06, ..., 8.0559757e-03,
        1.2192074e-02, 1.2017961e-02], dtype=float32),
 '007789b8-3a02-46ed-bf0c-c2bc53c25c88': array([ 0.00909383,  0.01260605, -0.00075678, ...,  0.00876781,
         0.01039122,  0.01402604], dtype=float32),
 'c786f51f-2cdf-46c1-a2cd-19fd7ef0debd': array([0.00778035, 0.01285475, 0.00292387, ..., 0.00904687, 0.01014857,
        0.01316868], dtype=float32),
 'a9c23b07-548a-41c8-a98a-47ed7562f2f3': array([0.00750461, 0.01262685, 0.0025786 , ..., 0.00749782, 0.00827433,
        0.01408081], dtype=float32),
 '3d208da3-6d20-4a03-8155-9db44c046915': array([0.00941411, 0.01454678, 0.00105687, ..., 0.00776487, 0.01024375,
        0.01047432], dtype=float32),
 '804dff48-d701-4370-8714-bed62b88ac88': array([0.00545353, 0.00874447, 0.00201811, ..., 0.00840736, 0.00732157,
        0.01395437], dtype=float32),
 'a0a704d0-8e6c-4fca-98da-f7179ede5468': array([ 0.00956008,  0.01236158, -0.00017656, ...,  0.00809395,
         0.00944173,  0.01090325], dtype=float32),
 '1775606a-bb68-4899-b5eb-8a2bda420f0c': array([0.00864292, 0.01577485, 0.00090284, ..., 0.00654832, 0.01062177,
        0.00977087], dtype=float32),
 'cb48aff9-4c10-4018-bebb-a6b535029dbb': array([0.00754298, 0.01247974, 0.00381448, ..., 0.00844781, 0.00970222,
        0.01330516], dtype=float32),
 '36e2d274-664d-47ca-abb6-8cb47ab28dfd': array([0.00916198, 0.01317058, 0.00027235, ..., 0.00901416, 0.00826399,
        0.012453  ], dtype=float32),
 '4ecf75e3-bd37-4031-9e1b-9ab2cbad30c1': array([ 0.00927503,  0.01190586, -0.00067125, ...,  0.00810249,
         0.0103425 ,  0.01200704], dtype=float32),
 '8a908812-60e5-4a89-a54e-e0890f48b96c': array([0.00977874, 0.01311103, 0.00059617, ..., 0.00897229, 0.00813069,
        0.01127137], dtype=float32),
 'ac8a702d-43cf-4ae3-96b7-9c61259a184f': array([0.00818892, 0.01425933, 0.0036118 , ..., 0.00851763, 0.0092099 ,
        0.01351353], dtype=float32),
 'eb38d613-d76c-44e4-9191-8a4f39e50c35': array([0.00854565, 0.01473747, 0.00024516, ..., 0.00714529, 0.0104988 ,
        0.01125856], dtype=float32),
 '7708a23e-7f3a-4786-afbf-84dbe6afa7b9': array([0.00915992, 0.01333845, 0.00222793, ..., 0.00793866, 0.01285954,
        0.01210145], dtype=float32),
 '0dcb8874-ade4-48bf-b84d-0136b6707032': array([0.00922106, 0.01554946, 0.00105115, ..., 0.00798654, 0.01149349,
        0.01159778], dtype=float32),
 'e84f46f7-f640-4e32-a724-23f423f453d5': array([ 0.00959731,  0.01073418, -0.00039681, ...,  0.00810949,
         0.00903798,  0.01235813], dtype=float32),
 'd1f5bea4-acff-44f5-94a6-36d48096ac34': array([0.0101825 , 0.01367243, 0.00129957, ..., 0.00788299, 0.01285167,
        0.01158617], dtype=float32),
 '43909cf9-39b5-49b2-a673-a2076c383ba6': array([ 1.07555641e-02,  1.52067477e-02, -3.77436918e-05, ...,
         7.40093505e-03,  1.33698145e-02,  1.08567011e-02], dtype=float32),
 '109ced3b-1510-49ab-82b3-7a5541fb7ad2': array([1.0109479e-02, 1.2035880e-02, 7.4602154e-05, ..., 8.5130613e-03,
        1.3238574e-02, 1.0847782e-02], dtype=float32),
 '77c27610-b494-43ef-9359-59115ecc58f8': array([0.01126263, 0.01581525, 0.00036905, ..., 0.00770486, 0.01253867,
        0.01189416], dtype=float32),
 'aa62c62f-5af9-48d1-ac8c-2884ef7fb92b': array([0.00925707, 0.01274404, 0.00096475, ..., 0.01074868, 0.01209568,
        0.01171165], dtype=float32),
 '08d1df87-28bd-4dce-b376-a044b5ddaa40': array([0.01073584, 0.01194006, 0.00026732, ..., 0.00839274, 0.01312565,
        0.01053093], dtype=float32),
 '5814ce14-79ac-4c3a-940c-155f7bac57b2': array([0.00889294, 0.01359445, 0.0019435 , ..., 0.00817073, 0.01172638,
        0.01187344], dtype=float32),
 'c615f2c4-a12e-487a-99c6-c10c4f6c6f18': array([0.00936393, 0.01281741, 0.00177564, ..., 0.00773468, 0.01255006,
        0.01169035], dtype=float32),
 '522b0555-4f88-4c94-9851-9f3ad987a611': array([0.00500817, 0.01298262, 0.00054925, ..., 0.00636101, 0.00620382,
        0.01448339], dtype=float32),
 '24b717ce-a070-42ce-a502-f0726379e0fc': array([0.00932879, 0.01216709, 0.00057498, ..., 0.00853478, 0.01199543,
        0.01113517], dtype=float32),
 'd15d0ba4-ef7f-4f7b-86a3-d11aaa920e8b': array([0.00894261, 0.01731315, 0.00134598, ..., 0.006299  , 0.01063857,
        0.0099283 ], dtype=float32),
 '926c7ed9-b16b-4b6e-b612-5a5226f7ece2': array([0.00778933, 0.01319147, 0.00238576, ..., 0.00637459, 0.00833034,
        0.01153997], dtype=float32),
 'b3f87490-46ee-4049-93a7-051d1052852e': array([0.00955553, 0.01385794, 0.00096029, ..., 0.00799141, 0.01027199,
        0.01253553], dtype=float32),
 '7e8b1071-3b26-403e-87f4-a21cd329f00c': array([0.00983615, 0.01248005, 0.00181705, ..., 0.00787841, 0.00829925,
        0.01188513], dtype=float32),
 '9afd9ced-d3f7-417a-9386-897a19688836': array([0.00788743, 0.01263752, 0.00441536, ..., 0.00332166, 0.00499903,
        0.01056548], dtype=float32),
 'a1a6fa93-3ddf-4c17-91d3-39e913c9e923': array([0.00825019, 0.01390463, 0.00240665, ..., 0.00750504, 0.01070582,
        0.00966347], dtype=float32),
 '78beb4a7-4b88-4dbe-ad48-46d66181d2e6': array([ 0.01021562,  0.0128456 , -0.00018211, ...,  0.00854291,
         0.01110597,  0.01092604], dtype=float32),
 'd511845f-9cd4-4a97-aec3-497c586ab97f': array([0.00881121, 0.01260572, 0.00135784, ..., 0.00584848, 0.01044837,
        0.01105107], dtype=float32),
 '4a1d5258-7f67-46e2-ae2b-8d9bf89ccb37': array([0.00809941, 0.01384615, 0.00326418, ..., 0.00879887, 0.00991903,
        0.01319294], dtype=float32),
 '8ffa7ca7-bfc1-4ea7-aad3-2c9f5c5163f3': array([0.00844262, 0.01236064, 0.00247445, ..., 0.00937366, 0.0094898 ,
        0.01420313], dtype=float32),
 '59905711-8a85-4e60-ad55-33081122374d': array([0.00943577, 0.01239231, 0.00282367, ..., 0.00632402, 0.0126639 ,
        0.01128014], dtype=float32),
 '390341e7-aed0-4f61-8175-787a2dbcbf7f': array([0.00781622, 0.01354818, 0.00163742, ..., 0.008103  , 0.00989858,
        0.01268172], dtype=float32),
 '9770dbe1-8cad-467c-a22c-484cfa719043': array([ 0.01065944,  0.01378305, -0.00120347, ...,  0.01002394,
         0.01281789,  0.01165302], dtype=float32),
 'c10aa2da-8b3b-445c-a4a2-ccf9c8155813': array([0.00894732, 0.012794  , 0.00047953, ..., 0.00817349, 0.01118963,
        0.01217199], dtype=float32),
 '6536665e-e15d-44af-9af6-0f91d6db60ed': array([0.01105827, 0.01508709, 0.0004307 , ..., 0.0062448 , 0.01309699,
        0.01201827], dtype=float32),
 '40431dd5-d1ff-4d94-b0bb-f767b724c71a': array([0.00826728, 0.01455693, 0.00180744, ..., 0.00878736, 0.01104615,
        0.0114919 ], dtype=float32),
 '0e7ac44f-b700-47fa-88ad-60a7d4897b06': array([0.0084896 , 0.01356455, 0.00123088, ..., 0.00795019, 0.01115112,
        0.01071704], dtype=float32),
 '3f6088fe-3c0e-4835-bb03-7e9398f63438': array([ 0.0094568 ,  0.01415326, -0.00028128, ...,  0.00886739,
         0.01051171,  0.01195346], dtype=float32),
 'fafe73a1-168a-4855-9e51-e070182a1bd2': array([0.00694651, 0.01257352, 0.002869  , ..., 0.00857152, 0.00930219,
        0.01312106], dtype=float32),
 '74b78f41-24db-4a63-b36e-498c5032a74d': array([0.01022327, 0.01469896, 0.00241043, ..., 0.00917865, 0.00721322,
        0.00932919], dtype=float32),
 '231708e6-ec4e-465b-a3cf-a75a0d6506a7': array([0.01033816, 0.01472816, 0.00161057, ..., 0.00744643, 0.01286741,
        0.0115717 ], dtype=float32),
 '995e54b9-e622-4620-8ae6-c96a8e57ed5d': array([0.00891684, 0.01312725, 0.0035857 , ..., 0.00935953, 0.0130495 ,
        0.01171489], dtype=float32),
 'a59e8ee7-8cd7-448d-9039-4ec0d960a29c': array([0.0082    , 0.01150694, 0.00335357, ..., 0.00971998, 0.00940312,
        0.01285793], dtype=float32),
 '11bc8a3d-a4d0-4bc6-801e-92e8a0d7753d': array([0.00937137, 0.01052292, 0.00015585, ..., 0.00825924, 0.00976105,
        0.01361968], dtype=float32),
 '6ec26d6b-1d55-4ba0-bcf1-5e3002d4eceb': array([0.00804934, 0.01337447, 0.00231203, ..., 0.00880404, 0.010321  ,
        0.01194963], dtype=float32),
 '39e82289-f8f6-452a-873c-f14ad493872c': array([0.00892721, 0.01444762, 0.00201072, ..., 0.00784287, 0.01340694,
        0.01208549], dtype=float32),
 '6a68ccb3-6d2d-4fc4-aae7-c47de410e4be': array([0.0099039 , 0.01334393, 0.00078993, ..., 0.00764152, 0.01128712,
        0.01216228], dtype=float32),
 '59578dee-e609-4e02-a509-fd49396c0555': array([0.0083615 , 0.02207722, 0.00258404, ..., 0.00690749, 0.01316805,
        0.01309685], dtype=float32),
 'fa95bf8f-e579-4c1c-8f5d-889dd071e858': array([0.01032128, 0.01671697, 0.00023221, ..., 0.0052    , 0.01170321,
        0.0099794 ], dtype=float32),
 '32d7ce73-89db-4902-9c35-4ef6ab79326c': array([ 0.01066524,  0.0119069 , -0.00056495, ...,  0.00834904,
         0.01389595,  0.01139129], dtype=float32),
 '164fb727-8dd4-4b71-bba6-541dec50e44d': array([0.00885366, 0.01556199, 0.00445518, ..., 0.00761459, 0.01318389,
        0.01261029], dtype=float32),
 '0e414eb3-83b5-4cd4-83db-ea94ddb8c358': array([0.01041542, 0.01693824, 0.00368784, ..., 0.00543002, 0.01460901,
        0.0090063 ], dtype=float32),
 'b33d312d-af36-4108-875f-01426841ed4f': array([0.00832719, 0.01489512, 0.00202598, ..., 0.00814715, 0.00925418,
        0.0124594 ], dtype=float32),
 'a1a6bb0f-18ef-49d5-a138-b5673b21467b': array([ 0.01162036,  0.01540985, -0.00079389, ...,  0.00733105,
         0.01303091,  0.01092656], dtype=float32),
 '80a351a0-7957-4493-af45-7ea5d4020889': array([0.0083085 , 0.012897  , 0.0017367 , ..., 0.00766546, 0.00988276,
        0.01230239], dtype=float32),
 'af62098a-1ffd-499b-bc2d-4d1b2bcc33ad': array([0.00682243, 0.01093788, 0.00137508, ..., 0.00795549, 0.008594  ,
        0.01261516], dtype=float32),
 '799fef32-0497-43a8-b80d-7a8f711f4dc1': array([ 0.00963682,  0.01283386, -0.00061692, ...,  0.0088748 ,
         0.01079933,  0.01157349], dtype=float32),
 '99f2261f-209e-4464-a17a-ffeaa1a9910e': array([0.00840118, 0.01353192, 0.00039192, ..., 0.00727549, 0.0099307 ,
        0.01271452], dtype=float32),
 '790ea6e3-f4e2-4f2a-a664-5929e182483c': array([ 0.01057663,  0.01322826, -0.00255911, ...,  0.01000271,
         0.01739805,  0.00990471], dtype=float32),
 '22573003-04d1-43ea-9b4b-1bf6eca10816': array([0.00825852, 0.01353369, 0.00245795, ..., 0.00798511, 0.01045555,
        0.01214993], dtype=float32),
 '4e7c4335-0c66-4c85-a944-e7786df6d466': array([0.00915817, 0.01288693, 0.0009445 , ..., 0.00911086, 0.00974612,
        0.01309474], dtype=float32),
 '6c0426f1-124b-4713-8585-a7c4f1782142': array([ 0.01153688,  0.01609916, -0.00180658, ...,  0.00890771,
         0.01389578,  0.00932434], dtype=float32),
 '4631051f-2d9e-4d1e-a343-6e536f3c32c2': array([ 0.01004535,  0.01446741, -0.00036311, ...,  0.00694497,
         0.0126019 ,  0.01102365], dtype=float32),
 '57149daf-2fb7-4035-a7bc-4185eacea3cc': array([0.00901714, 0.01327867, 0.00049256, ..., 0.00862012, 0.00999995,
        0.01295925], dtype=float32),
 'adfd03e5-79c7-4b1b-a0a0-5b9999dc79bf': array([ 1.2875945e-02,  1.5878219e-02, -9.4471761e-05, ...,
         7.3841223e-03,  9.6470062e-03,  1.1293355e-02], dtype=float32),
 '2016ca8f-1c3e-481a-8b25-5586188a2a42': array([0.00779083, 0.01402382, 0.00306324, ..., 0.00692903, 0.01043971,
        0.01273518], dtype=float32),
 '5f097882-989c-4446-844a-e6e709312889': array([ 0.00864828,  0.01203627, -0.00138104, ...,  0.00780452,
         0.00880459,  0.01215846], dtype=float32),
 '06890ee8-ff1b-491b-b317-3d95ffbbf90d': array([ 0.01061456,  0.01380732, -0.0003368 , ...,  0.0083028 ,
         0.01072553,  0.01149083], dtype=float32),
 '5bfa8251-ac31-47c6-81da-708c16ff439c': array([0.0084215 , 0.0127786 , 0.00071559, ..., 0.00697949, 0.00948902,
        0.01208414], dtype=float32),
 '0582fc61-1c6b-4e39-bf6e-8b48c1874042': array([0.00695698, 0.0134005 , 0.00297351, ..., 0.00804527, 0.00884538,
        0.01303698], dtype=float32),
 '3718adad-ee7d-4a3e-b642-1dbb15b48904': array([0.00860603, 0.01538721, 0.00053859, ..., 0.00850584, 0.01073143,
        0.01217062], dtype=float32),
 'a50ed31e-45d2-4321-9dab-6d08b402008a': array([0.00805454, 0.01052723, 0.00074199, ..., 0.00842236, 0.00924736,
        0.01281565], dtype=float32),
 'f791042c-8dc6-4e89-abf3-be3f36d3c878': array([ 0.01048261,  0.01586019, -0.00057007, ...,  0.00936306,
         0.01151107,  0.01152203], dtype=float32),
 'a3e7e755-4c7b-4e04-bcd0-58da64505316': array([0.00915981, 0.01474781, 0.00344912, ..., 0.00717409, 0.00880652,
        0.01424533], dtype=float32),
 '70b17f3e-74f1-4819-b4b0-fa52c4b3a291': array([0.00742725, 0.01478465, 0.00328709, ..., 0.007749  , 0.00852534,
        0.01277442], dtype=float32),
 'c7483061-4306-4cac-9430-8b2d9034342f': array([0.00947481, 0.01485393, 0.00064403, ..., 0.00638616, 0.01119618,
        0.00932004], dtype=float32),
 'f017d30a-9f5f-462a-8499-2c8942f541f1': array([0.00543697, 0.01218221, 0.00426693, ..., 0.00723107, 0.00722679,
        0.01233295], dtype=float32),
 '4622ce18-db34-41ef-9c76-37c8aaf6fa6a': array([0.00864815, 0.01296295, 0.00186049, ..., 0.0080316 , 0.01340102,
        0.01225323], dtype=float32),
 '2c6e8f03-adbd-42a6-b390-91fb898324e4': array([0.00921014, 0.0162795 , 0.00043176, ..., 0.00842719, 0.01067563,
        0.01007823], dtype=float32),
 '6226dcd6-c2bb-484b-9d3a-6b25c07125eb': array([0.00927125, 0.01550138, 0.00233659, ..., 0.00841627, 0.01202028,
        0.01110643], dtype=float32),
 '5de5f04e-c3ff-4aaa-aa7c-3be4345d9091': array([0.00739888, 0.01267474, 0.00318042, ..., 0.00946442, 0.00960725,
        0.01394324], dtype=float32),
 '211d9af0-756f-490f-9d60-02720538a031': array([0.00735787, 0.01282685, 0.00208016, ..., 0.00895944, 0.0088749 ,
        0.0121988 ], dtype=float32),
 'e21e7c08-06d2-4e6a-b2fa-f1a2c478e3ae': array([0.0095131 , 0.0126827 , 0.0032852 , ..., 0.00630314, 0.01436115,
        0.01061625], dtype=float32),
 '93c4367d-e443-401b-b75a-c7a22ed9154c': array([0.01038172, 0.01513951, 0.00032645, ..., 0.00788272, 0.01259722,
        0.01109294], dtype=float32),
 '0cb0a7ed-78c3-4e64-826e-2a905d365a28': array([0.00872739, 0.0143866 , 0.00240191, ..., 0.00776033, 0.01198833,
        0.01257834], dtype=float32),
 'de5f3f9c-e92a-4380-be81-01363f83456c': array([ 0.01000138,  0.01252282, -0.00063758, ...,  0.00851654,
         0.01193711,  0.01214961], dtype=float32),
 'a9ef10c6-c322-4438-8c4b-96ece8b8f5d1': array([0.00842999, 0.00909   , 0.00263663, ..., 0.00683565, 0.0106804 ,
        0.0116617 ], dtype=float32),
 '87e0de36-a2e4-44bb-9aaf-f26d99ecde70': array([0.00950733, 0.01463321, 0.00115175, ..., 0.0066205 , 0.0120251 ,
        0.01126883], dtype=float32),
 'a1142d44-6ffe-4fb4-9e64-98e9a107dc15': array([0.00566687, 0.013267  , 0.00225093, ..., 0.00691327, 0.00397035,
        0.01177432], dtype=float32),
 '1f2318a2-0673-48cc-b078-bad35db86926': array([0.00932921, 0.01253357, 0.00233604, ..., 0.00887159, 0.00916969,
        0.01066148], dtype=float32),
 '8c93c204-737b-4c27-84f3-54f6a4311f5b': array([ 0.0113388 ,  0.01357653, -0.0025944 , ...,  0.00959482,
         0.0103876 ,  0.00941134], dtype=float32),
 '49a894cf-2ebd-40f5-8b70-9b6d680168b4': array([0.00873026, 0.01671417, 0.00129667, ..., 0.00652172, 0.00947153,
        0.01115248], dtype=float32),
 '35b8625a-eab8-437c-8886-36d455e03edf': array([0.00713687, 0.01204677, 0.00302312, ..., 0.00792024, 0.0052818 ,
        0.01081563], dtype=float32),
 '2d1f3b94-b1b3-44a2-a52f-5f0e967023bd': array([0.01014771, 0.01453213, 0.00042388, ..., 0.00843485, 0.01256462,
        0.01328205], dtype=float32),
 '4f32a747-3d3e-4a1c-ad7b-0ffbe8b72949': array([0.00972266, 0.01437956, 0.00369825, ..., 0.007758  , 0.01123762,
        0.01204819], dtype=float32),
 'cd684008-1d0d-4697-8b0d-d808c3b6f473': array([0.00994281, 0.01576333, 0.00015485, ..., 0.00733894, 0.01406014,
        0.01072369], dtype=float32),
 'c9715134-4aa9-4ad6-998d-9ae4bbed81db': array([0.00708753, 0.01388178, 0.00274683, ..., 0.00902566, 0.00918568,
        0.01363633], dtype=float32),
 '244de001-03e6-4cd4-87a4-c5f5ee6092d0': array([0.00569633, 0.01168373, 0.00395883, ..., 0.00739696, 0.00785121,
        0.01290278], dtype=float32),
 'f90a1d9e-5523-42c6-b856-8bf87cc653ae': array([0.00846879, 0.01123721, 0.0006326 , ..., 0.00878261, 0.00835184,
        0.01180939], dtype=float32),
 'a17a8547-7f98-469f-b4bd-9f53f6da26d0': array([ 0.00976611,  0.00983754, -0.00195034, ...,  0.01098012,
         0.01077573,  0.0121417 ], dtype=float32),
 '0f89318e-a9b2-4abf-84b0-4aeadc3d0056': array([0.00702019, 0.01318983, 0.00253605, ..., 0.00650898, 0.00731948,
        0.01344537], dtype=float32),
 'a3939a45-f722-4114-8587-c43ceb77b0ce': array([0.00979351, 0.01385207, 0.00154925, ..., 0.00764902, 0.00814053,
        0.01064222], dtype=float32),

In [ ]:
# we want all our artist to have a vector representation
def knn_search(vectors: Dict[str, np.array], query_vector: np.array, k: int) -> Dict[str, List[str]]:
  """
  KNN search for the k nearest neighbors of the query vector in the given L2 normalized vectors.
  """

  agg_vectors = np.array(list(vectors.values()))

  # compute pairwise distances
  distances = np.linalg.norm(agg_vectors - query_vector, axis=1)

  # get top k indices
  top_k_indices = np.argsort(distances)[:k]
  
  reg_top_k_indices = [k.item() for k in top_k_indices]

  # get top k artists
  top_k_artists = [list(vectors.keys())[i] for i in reg_top_k_indices]

  return top_k_artists

def get_artist_name(artist_id: str) -> str:
  return emb_idx_df[emb_idx_df['ArtistIDList'].apply(lambda x: artist_id in x)]['Artists'].iloc[0][0]['name']

artist_id = '85de2a90-ea44-473f-af2f-2c22dcc99064'
print(f"Searching 10 nearest neighbors for {artist_id} (Centroid)")
result_ids = knn_search(artist_centroid, artist_centroid[artist_id], 10)
for result_id in result_ids:
  print(get_artist_name(result_id))

Searching 10 nearest neighbors for fdf7d27c-f263-4739-96b9-67567fe47df7 (Centroid)
森羅万象
ふぉれすとぴれお
pikapika
株式会社虎の穴
SOUND HOLIC
Amorevole
紺碧studio
セブンスヘブンMAXION
博丽神社事务所
COOL&CREATE